import { executeQuery, formatQueryResult, createErrorResponse, ToolResponse } from '../lib/utils';

export interface handleSQLCache {
  beginTime?: string;
  endTime?: string;
  statementHash?: string;
  appName?: string;
  appSource?: string;
  timeAggregateBy?: string;
  orderBy?: string;
}

export async function handleSQLCache(params: handleSQLCache = {}): Promise<ToolResponse> {
  try {
    // 파라미터 보정: 빈값(null, undefined, '')이면 기본값 할당
    const beginTime = params?.beginTime ? `'${params.beginTime}'` : `'C-H1'`;
    const endTime = params?.endTime ? `'${params.endTime}'` : `'C'`;    
    const statementHash = params?.statementHash ? `'${params.statementHash}'` : `'%'`;
    const appName = params?.appName ? `'${params.appName}'` : `'%'`;
    const appSource = params?.appSource ? `'${params.appSource}'` : `'%'`;
    
    // timeAggregateBy 허용값 체크
    let rawTimeAggregateBy = params?.timeAggregateBy;
    let allowedTimeAggregates = ['HOUR', 'DAY', 'HOUR_OF_DAY', 'NONE'];
    let isTS = typeof rawTimeAggregateBy === 'string' && /^TS\d+$/.test(rawTimeAggregateBy);
    if (rawTimeAggregateBy && !allowedTimeAggregates.includes(rawTimeAggregateBy) && !isTS) {
      return createErrorResponse(
        `timeAggregateBy 파라미터는 'HOUR', 'DAY', 'HOUR_OF_DAY', /^TS\\d+$/, 'NONE' 만 허용합니다. (입력값: ${rawTimeAggregateBy})`
      );
    }
    const timeAggregateBy = rawTimeAggregateBy ? `'${rawTimeAggregateBy}'` : `'TS60'`;
    
    // orderBy 허용값 체크
    let rawOrderBy = params?.orderBy;
    let allowedOrderBy = [
      'TIME', 'EXEC', 'PREP', 'CURSOR', 'OPEN', 'FETCH', 'LOCK',
      'EXECUTIONS', 'RECORDS', 'NETWORK_COUNT', 'NETWORK_SIZE',
      'NETWORK_TIME', 'MEMORY', 'MEM_PER_EXEC', 'PLAN_MEM',
      'THREAD', 'BC_MISS_COUNT', 'BC_IO_SIZE'
    ];
    if (rawOrderBy && !allowedOrderBy.includes(rawOrderBy)) {
      return createErrorResponse(
        `orderBy 파라미터는 다음 값만 허용합니다: ${allowedOrderBy.join(', ')} (입력값: ${rawOrderBy})`
      );
    }
    const orderBy = rawOrderBy ? `'${rawOrderBy}'` : `'TIME'`; 

    let query = `
WITH 

BASIS_INFO AS
( SELECT
    CASE
      WHEN BEGIN_TIME =    'C'                             THEN CURRENT_TIMESTAMP
      WHEN BEGIN_TIME LIKE 'C-S%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(BEGIN_TIME, 'C-S'))
      WHEN BEGIN_TIME LIKE 'C-M%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(BEGIN_TIME, 'C-M') * 60)
      WHEN BEGIN_TIME LIKE 'C-H%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(BEGIN_TIME, 'C-H') * 3600)
      WHEN BEGIN_TIME LIKE 'C-D%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(BEGIN_TIME, 'C-D') * 86400)
      WHEN BEGIN_TIME LIKE 'C-W%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(BEGIN_TIME, 'C-W') * 86400 * 7)
      WHEN BEGIN_TIME LIKE 'E-S%'                          THEN ADD_SECONDS(TO_TIMESTAMP(END_TIME, 'YYYY/MM/DD HH24:MI:SS'), -SUBSTR_AFTER(BEGIN_TIME, 'E-S'))
      WHEN BEGIN_TIME LIKE 'E-M%'                          THEN ADD_SECONDS(TO_TIMESTAMP(END_TIME, 'YYYY/MM/DD HH24:MI:SS'), -SUBSTR_AFTER(BEGIN_TIME, 'E-M') * 60)
      WHEN BEGIN_TIME LIKE 'E-H%'                          THEN ADD_SECONDS(TO_TIMESTAMP(END_TIME, 'YYYY/MM/DD HH24:MI:SS'), -SUBSTR_AFTER(BEGIN_TIME, 'E-H') * 3600)
      WHEN BEGIN_TIME LIKE 'E-D%'                          THEN ADD_SECONDS(TO_TIMESTAMP(END_TIME, 'YYYY/MM/DD HH24:MI:SS'), -SUBSTR_AFTER(BEGIN_TIME, 'E-D') * 86400)
      WHEN BEGIN_TIME LIKE 'E-W%'                          THEN ADD_SECONDS(TO_TIMESTAMP(END_TIME, 'YYYY/MM/DD HH24:MI:SS'), -SUBSTR_AFTER(BEGIN_TIME, 'E-W') * 86400 * 7)
      WHEN BEGIN_TIME =    'MIN'                           THEN TO_TIMESTAMP('1000/01/01 00:00:00', 'YYYY/MM/DD HH24:MI:SS')
      WHEN SUBSTR(BEGIN_TIME, 1, 1) NOT IN ('C', 'E', 'M') THEN TO_TIMESTAMP(BEGIN_TIME, 'YYYY/MM/DD HH24:MI:SS')
    END BEGIN_TIME,
    CASE
      WHEN END_TIME =    'C'                             THEN CURRENT_TIMESTAMP
      WHEN END_TIME LIKE 'C-S%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(END_TIME, 'C-S'))
      WHEN END_TIME LIKE 'C-M%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(END_TIME, 'C-M') * 60)
      WHEN END_TIME LIKE 'C-H%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(END_TIME, 'C-H') * 3600)
      WHEN END_TIME LIKE 'C-D%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(END_TIME, 'C-D') * 86400)
      WHEN END_TIME LIKE 'C-W%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(END_TIME, 'C-W') * 86400 * 7)
      WHEN END_TIME LIKE 'B+S%'                          THEN ADD_SECONDS(TO_TIMESTAMP(BEGIN_TIME, 'YYYY/MM/DD HH24:MI:SS'), SUBSTR_AFTER(END_TIME, 'B+S'))
      WHEN END_TIME LIKE 'B+M%'                          THEN ADD_SECONDS(TO_TIMESTAMP(BEGIN_TIME, 'YYYY/MM/DD HH24:MI:SS'), SUBSTR_AFTER(END_TIME, 'B+M') * 60)
      WHEN END_TIME LIKE 'B+H%'                          THEN ADD_SECONDS(TO_TIMESTAMP(BEGIN_TIME, 'YYYY/MM/DD HH24:MI:SS'), SUBSTR_AFTER(END_TIME, 'B+H') * 3600)
      WHEN END_TIME LIKE 'B+D%'                          THEN ADD_SECONDS(TO_TIMESTAMP(BEGIN_TIME, 'YYYY/MM/DD HH24:MI:SS'), SUBSTR_AFTER(END_TIME, 'B+D') * 86400)
      WHEN END_TIME LIKE 'B+W%'                          THEN ADD_SECONDS(TO_TIMESTAMP(BEGIN_TIME, 'YYYY/MM/DD HH24:MI:SS'), SUBSTR_AFTER(END_TIME, 'B+W') * 86400 * 7)
      WHEN END_TIME =    'MAX'                           THEN TO_TIMESTAMP('9999/12/31 00:00:00', 'YYYY/MM/DD HH24:MI:SS')
      WHEN SUBSTR(END_TIME, 1, 1) NOT IN ('C', 'B', 'M') THEN TO_TIMESTAMP(END_TIME, 'YYYY/MM/DD HH24:MI:SS')
    END END_TIME,
    TIMEZONE,
    TIMESTAMP_TYPE,
    HOST,
    PORT,
    SCHEMA_NAME,
    TABLE_LOCATION,
    STATEMENT_HASH,
    TABLE_NAME,
    SQL_PATTERN,
    SQL_TYPE,
    DB_USER,
    APP_NAME,
    APP_SOURCE,
    INV_REASON,
    IS_DISTRIBUTED_EXECUTION,
    IS_PINNED_PLAN,
    STORE,
    ENGINES,
    MIN_PLAN_SIZE_KB,
    ONLY_CROSS_NODE_JOINS,
    SHARING_TYPE,
    EXCLUDE_CURRENT_RANGE_RESTRICTION,
    IS_INTERNAL,
    DISPLAY_STATEMENT_TEXT,
    DATA_SOURCE,
    AGGREGATE_BY,
    MAP(TIME_AGGREGATE_BY,
      'NONE',        'YYYY/MM/DD HH24:MI:SS',
      'HOUR',        'YYYY/MM/DD HH24',
      'DAY',         'YYYY/MM/DD (DY)',
      'HOUR_OF_DAY', 'HH24',
      TIME_AGGREGATE_BY ) TIME_AGGREGATE_BY,
    ORDER_BY
  FROM
  ( SELECT                                                      /* Modification section */
      ${beginTime} BEGIN_TIME,                  /* YYYY/MM/DD HH24:MI:SS timestamp, C, C-S<seconds>, C-M<minutes>, C-H<hours>, C-D<days>, C-W<weeks>, E-S<seconds>, E-M<minutes>, E-H<hours>, E-D<days>, E-W<weeks>, MIN */
      ${endTime} END_TIME,                    /* YYYY/MM/DD HH24:MI:SS timestamp, C, C-S<seconds>, C-M<minutes>, C-H<hours>, C-D<days>, C-W<weeks>, B+S<seconds>, B+M<minutes>, B+H<hours>, B+D<days>, B+W<weeks>, MAX */
      'SERVER' TIMEZONE,                              /* SERVER, UTC */
      'EXEC' TIMESTAMP_TYPE,                       /* SERVER, EXEC, PREP */
      '%' HOST,
      '%' PORT,
      '%' SCHEMA_NAME,
      '%' TABLE_LOCATION,
      ${statementHash} STATEMENT_HASH,
      '%' TABLE_NAME,
      '%' SQL_PATTERN,                             /* only works when DISPLAY_STATEMENT_TEXT = 'X' is set */
      '%' SQL_TYPE,                                /* only works when DISPLAY_STATEMENT_TEXT = 'X' is set */
      '%' DB_USER,
      ${appName} APP_NAME,
      ${appSource} APP_SOURCE,
      '%' INV_REASON,
      '%' IS_DISTRIBUTED_EXECUTION,                    /* TRUE, FALSE, % */
      '%' IS_PINNED_PLAN,
      '%' IS_INTERNAL,
      ' ' ONLY_CROSS_NODE_JOINS,
      '%' SHARING_TYPE,
      '%' STORE,
      '%' ENGINES,
      -1 MIN_PLAN_SIZE_KB,
      ' ' EXCLUDE_CURRENT_RANGE_RESTRICTION,      /* only works when DISPLAY_STATEMENT_TEXT = 'X' is set */
      'X' DISPLAY_STATEMENT_TEXT,
      'HISTORY' DATA_SOURCE,      /* CURRENT, HISTORY, RESET, STATISTICS */
      'TIME, HOST, PORT, HASH, SQL_TYPE, PLAN_ID, STORE, INV_REASON, SHARING_TYPE, DIST, SCHEMA, LOCATION, INTERNAL, TABLES, APP_NAME, APP_SOURCE, PINNED, ENGINES' AGGREGATE_BY,  
                                  /* TIME, HOST, PORT, HASH, SQL_TYPE, PLAN_ID, STORE, INV_REASON, SHARING_TYPE, DIST, SCHEMA, LOCATION, INTERNAL, TABLES, APP_NAME, APP_SOURCE, PINNED, ENGINES or comma separated list, NONE for no aggregation */
      ${timeAggregateBy} TIME_AGGREGATE_BY,   /* HOUR, DAY, HOUR_OF_DAY or database time pattern, TS<seconds> for time slice, NONE for no aggregation */
      ${orderBy} ORDER_BY       /* TIME, EXEC, PREP, CURSOR, OPEN, FETCH, LOCK, EXECUTIONS, RECORDS, NETWORK_COUNT, NETWORK_SIZE, NETWORK_TIME, MEMORY, MEM_PER_EXEC, PLAN_MEM, THREAD, BC_MISS_COUNT, BC_IO_SIZE */
    FROM
      DUMMY
  ) BI
),
SQL_CACHE AS
( SELECT
    'CURRENT' DATA_SOURCE,
    HOST,
    PORT,
    NULL SNAPSHOT_ID,
    SCHEMA_NAME,
    STATEMENT_HASH,
    PLAN_ID,
    USER_NAME,
    TO_VARCHAR(ACCESSED_TABLE_NAMES) ACCESSED_TABLE_NAMES,
    MAP(BI.DISPLAY_STATEMENT_TEXT, 'X', TO_VARCHAR(STATEMENT_STRING), '') STATEMENT_STRING,
    MAP(BI.DISPLAY_STATEMENT_TEXT, 'X', REPLACE(UPPER(LTRIM(MAP(SUBSTR(TO_VARCHAR(STATEMENT_STRING), 1, 2), '/*', SUBSTR(TO_VARCHAR(STATEMENT_STRING), LOCATE(TO_VARCHAR(STATEMENT_STRING), '*/') + 2), TO_VARCHAR(STATEMENT_STRING)), ' ({')), CHAR(10), ''), '') STATEMENT_STRING_CLEANED,
    TABLE_TYPES STORE,
    EXECUTION_ENGINE ENGINES,
    PLAN_SHARING_TYPE SHARING_TYPE,
    REFERENCE_COUNT,
    CURRENT_TIMESTAMP SERVER_TIMESTAMP,
    IS_DISTRIBUTED_EXECUTION,
    CASE WHEN COMPILATION_OPTIONS = 'STATEMENT HINT' OR IS_PINNED_PLAN = 'TRUE' THEN 'TRUE' ELSE FALSE END IS_PINNED_PLAN,
    IS_INTERNAL,
    EXECUTION_COUNT,
    TOTAL_RESULT_RECORD_COUNT,
    TOTAL_CURSOR_DURATION,
    TOTAL_EXECUTION_TIME,
    TOTAL_EXECUTION_OPEN_TIME,
    TOTAL_EXECUTION_FETCH_TIME,
    TOTAL_PREPARATION_TIME,
    PREPARATION_COUNT,
    TOTAL_LOCK_WAIT_DURATION,
    LAST_PREPARATION_TIMESTAMP,
    LAST_EXECUTION_TIMESTAMP,
    TOTAL_SERVICE_NETWORK_REQUEST_COUNT,
    TOTAL_SERVICE_NETWORK_REQUEST_DURATION,
    TOTAL_SERVICE_NETWORK_REQUEST_SIZE,
    TOTAL_BUFFER_CACHE_PAGE_MISS_COUNT,
    TOTAL_BUFFER_CACHE_IO_READ_SIZE,
    TOTAL_CALLED_THREAD_COUNT,
    TOTAL_EXECUTION_MEMORY_SIZE,
    TABLE_LOCATIONS TABLE_LOCATION,
    APPLICATION_SOURCE,
    APPLICATION_NAME,
    CASE 
      WHEN LAST_INVALIDATION_REASON LIKE 'OBJECT VERSION MISMATCH%' THEN 'OBJECT VERSION MISMATCH'
      WHEN LAST_INVALIDATION_REASON LIKE 'NON-USER-OID NOT FOUND%'  THEN 'NON-USER-OID NOT FOUND'
      ELSE LAST_INVALIDATION_REASON 
    END LAST_INVALIDATION_REASON,
    PLAN_MEMORY_SIZE
  FROM
    ( SELECT DISPLAY_STATEMENT_TEXT FROM BASIS_INFO ) BI,
    M_SQL_PLAN_CACHE
  UNION ALL
  SELECT
    'STATISTICS' DATA_SOURCE,
    HOST,
    PORT,
    NULL SNAPSHOT_ID,
    SCHEMA_NAME,
    STATEMENT_HASH,
    PLAN_ID,
    USER_NAME,
    TO_VARCHAR(ACCESSED_TABLE_NAMES) ACCESSED_TABLE_NAMES,
    MAP(BI.DISPLAY_STATEMENT_TEXT, 'X', TO_VARCHAR(STATEMENT_STRING), '') STATEMENT_STRING,
    MAP(BI.DISPLAY_STATEMENT_TEXT, 'X', REPLACE(UPPER(LTRIM(MAP(SUBSTR(TO_VARCHAR(STATEMENT_STRING), 1, 2), '/*', SUBSTR(TO_VARCHAR(STATEMENT_STRING), LOCATE(TO_VARCHAR(STATEMENT_STRING), '*/') + 2), TO_VARCHAR(STATEMENT_STRING)), ' ({')), CHAR(10), ''), '') STATEMENT_STRING_CLEANED,
    TABLE_TYPES STORE,
    EXECUTION_ENGINE ENGINES,
    PLAN_SHARING_TYPE SHARING_TYPE,
    REFERENCE_COUNT,
    CURRENT_TIMESTAMP SERVER_TIMESTAMP,
    IS_DISTRIBUTED_EXECUTION,
    CASE WHEN COMPILATION_OPTIONS = 'STATEMENT HINT' OR IS_PINNED_PLAN = 'TRUE' THEN 'TRUE' ELSE FALSE END,
    IS_INTERNAL,
    EXECUTION_COUNT,
    TOTAL_RESULT_RECORD_COUNT,
    TOTAL_CURSOR_DURATION,
    TOTAL_EXECUTION_TIME,
    TOTAL_EXECUTION_OPEN_TIME,
    TOTAL_EXECUTION_FETCH_TIME,
    TOTAL_PREPARATION_TIME,
    PREPARATION_COUNT,
    TOTAL_LOCK_WAIT_DURATION,
    LAST_PREPARATION_TIMESTAMP,
    LAST_EXECUTION_TIMESTAMP,
    TOTAL_SERVICE_NETWORK_REQUEST_COUNT,
    TOTAL_SERVICE_NETWORK_REQUEST_DURATION,
    TOTAL_SERVICE_NETWORK_REQUEST_SIZE,
    TOTAL_BUFFER_CACHE_PAGE_MISS_COUNT,
    TOTAL_BUFFER_CACHE_IO_READ_SIZE,
    TOTAL_CALLED_THREAD_COUNT,
    TOTAL_EXECUTION_MEMORY_SIZE,
    TABLE_LOCATIONS TABLE_LOCATION,
    APPLICATION_SOURCE,
    APPLICATION_NAME,
    CASE 
      WHEN LAST_INVALIDATION_REASON LIKE 'OBJECT VERSION MISMATCH%' THEN 'OBJECT VERSION MISMATCH'
      WHEN LAST_INVALIDATION_REASON LIKE 'NON-USER-OID NOT FOUND%'  THEN 'NON-USER-OID NOT FOUND'
      ELSE LAST_INVALIDATION_REASON 
    END LAST_INVALIDATION_REASON,
    PLAN_MEMORY_SIZE
  FROM
    ( SELECT DISPLAY_STATEMENT_TEXT FROM BASIS_INFO ) BI,
    M_SQL_PLAN_STATISTICS
  UNION ALL
  SELECT
    'RESET' DATA_SOURCE,
    HOST,
    PORT,
    NULL SNAPSHOT_ID,
    SCHEMA_NAME,
    STATEMENT_HASH,
    PLAN_ID,
    USER_NAME,
    TO_VARCHAR(ACCESSED_TABLE_NAMES) ACCESSED_TABLE_NAMES,
    MAP(BI.DISPLAY_STATEMENT_TEXT, 'X', TO_VARCHAR(STATEMENT_STRING), '') STATEMENT_STRING,
    MAP(BI.DISPLAY_STATEMENT_TEXT, 'X', REPLACE(UPPER(LTRIM(MAP(SUBSTR(TO_VARCHAR(STATEMENT_STRING), 1, 2), '/*', SUBSTR(TO_VARCHAR(STATEMENT_STRING), LOCATE(TO_VARCHAR(STATEMENT_STRING), '*/') + 2), TO_VARCHAR(STATEMENT_STRING)), ' ({')), CHAR(10), ''), '') STATEMENT_STRING_CLEANED,
    TABLE_TYPES STORE,
    EXECUTION_ENGINE ENGINES,
    PLAN_SHARING_TYPE SHARING_TYPE,
    REFERENCE_COUNT,
    CURRENT_TIMESTAMP SERVER_TIMESTAMP,
    IS_DISTRIBUTED_EXECUTION,
    CASE WHEN COMPILATION_OPTIONS = 'STATEMENT HINT' OR IS_PINNED_PLAN = 'TRUE' THEN 'TRUE' ELSE FALSE END IS_PINNED_PLAN,
    IS_INTERNAL,
    EXECUTION_COUNT,
    TOTAL_RESULT_RECORD_COUNT,
    TOTAL_CURSOR_DURATION,
    TOTAL_EXECUTION_TIME,
    TOTAL_EXECUTION_OPEN_TIME,
    TOTAL_EXECUTION_FETCH_TIME,
    TOTAL_PREPARATION_TIME,
    PREPARATION_COUNT,
    TOTAL_LOCK_WAIT_DURATION,
    LAST_PREPARATION_TIMESTAMP,
    LAST_EXECUTION_TIMESTAMP,
    TOTAL_SERVICE_NETWORK_REQUEST_COUNT,
    TOTAL_SERVICE_NETWORK_REQUEST_DURATION,
    TOTAL_SERVICE_NETWORK_REQUEST_SIZE,
    TOTAL_BUFFER_CACHE_PAGE_MISS_COUNT,
    TOTAL_BUFFER_CACHE_IO_READ_SIZE,
    TOTAL_CALLED_THREAD_COUNT,
    TOTAL_EXECUTION_MEMORY_SIZE,
    TABLE_LOCATIONS TABLE_LOCATION,
    APPLICATION_SOURCE,
    APPLICATION_NAME,
    CASE 
      WHEN LAST_INVALIDATION_REASON LIKE 'OBJECT VERSION MISMATCH%' THEN 'OBJECT VERSION MISMATCH'
      WHEN LAST_INVALIDATION_REASON LIKE 'NON-USER-OID NOT FOUND%'  THEN 'NON-USER-OID NOT FOUND'
      ELSE LAST_INVALIDATION_REASON 
    END LAST_INVALIDATION_REASON,
    PLAN_MEMORY_SIZE
  FROM
    ( SELECT DISPLAY_STATEMENT_TEXT FROM BASIS_INFO ) BI,
    M_SQL_PLAN_CACHE_RESET
  UNION ALL
  SELECT
    'HISTORY' DATA_SOURCE,
    HOST,
    PORT,
    SNAPSHOT_ID,
    SCHEMA_NAME,
    STATEMENT_HASH,
    PLAN_ID,
    USER_NAME,
    TO_VARCHAR(ACCESSED_TABLE_NAMES) ACCESSED_TABLE_NAMES,
    MAP(BI.DISPLAY_STATEMENT_TEXT, 'X', TO_VARCHAR(STATEMENT_STRING), '') STATEMENT_STRING,
    MAP(BI.DISPLAY_STATEMENT_TEXT, 'X', REPLACE(UPPER(LTRIM(MAP(SUBSTR(TO_VARCHAR(STATEMENT_STRING), 1, 2), '/*', SUBSTR(TO_VARCHAR(STATEMENT_STRING), LOCATE(TO_VARCHAR(STATEMENT_STRING), '*/') + 2), TO_VARCHAR(STATEMENT_STRING)), ' ({')), CHAR(10), ''), '') STATEMENT_STRING_CLEANED,
    TABLE_TYPES STORE,
    EXECUTION_ENGINE ENGINES,
    PLAN_SHARING_TYPE SHARING_TYPE,
    REFERENCE_COUNT,
    SERVER_TIMESTAMP,
    IS_DISTRIBUTED_EXECUTION,
    CASE WHEN COMPILATION_OPTIONS = 'STATEMENT HINT' OR IS_PINNED_PLAN = 'TRUE' THEN 'TRUE' ELSE FALSE END IS_PINNED_PLAN,
    IS_INTERNAL,
    MAX(EXECUTION_COUNT) EXECUTION_COUNT,
    MAX(TOTAL_RESULT_RECORD_COUNT) TOTAL_RESULT_RECORD_COUNT,
    MAX(TOTAL_CURSOR_DURATION) TOTAL_CURSOR_DURATION,
    MAX(TOTAL_EXECUTION_TIME) TOTAL_EXECUTION_TIME,
    MAX(TOTAL_EXECUTION_OPEN_TIME) TOTAL_EXECUTION_OPEN_TIME,
    MAX(TOTAL_EXECUTION_FETCH_TIME) TOTAL_EXECUTION_FETCH_TIME,
    MAX(TOTAL_PREPARATION_TIME) TOTAL_PREPARATION_TIME,
    MAX(PREPARATION_COUNT) PREPARATION_COUNT,
    MAX(TOTAL_LOCK_WAIT_DURATION) TOTAL_LOCK_WAIT_DURATION,
    MAX(LAST_PREPARATION_TIMESTAMP) LAST_PREPARATION_TIMESTAMP,
    MAX(LAST_EXECUTION_TIMESTAMP) LAST_EXECUTION_TIMESTAMP,
    MAX(TOTAL_SERVICE_NETWORK_REQUEST_COUNT) TOTAL_SERVICE_NETWORK_REQUEST_COUNT,
    MAX(TOTAL_SERVICE_NETWORK_REQUEST_DURATION) TOTAL_SERVICE_NETWORK_REQUEST_DURATION,
    MAX(TOTAL_SERVICE_NETWORK_REQUEST_SIZE) TOTAL_SERVICE_NETWORK_REQUEST_SIZE,
	MAX(TOTAL_BUFFER_CACHE_PAGE_MISS_COUNT) TOTAL_BUFFER_CACHE_PAGE_MISS_COUNT,
	MAX(TOTAL_BUFFER_CACHE_IO_READ_SIZE) TOTAL_BUFFER_CACHE_IO_READ_SIZE,
    MAX(TOTAL_CALLED_THREAD_COUNT) TOTAL_CALLED_THREAD_COUNT,
    MAX(TOTAL_EXECUTION_MEMORY_SIZE) TOTAL_EXECUTION_MEMORY_SIZE,
    TABLE_LOCATIONS TABLE_LOCATION,
    APPLICATION_SOURCE,
    APPLICATION_NAME,
    CASE 
      WHEN LAST_INVALIDATION_REASON LIKE 'NON-USER-OID NOT FOUND%' THEN 'NON-USER-OID NOT FOUND' 
      WHEN LAST_INVALIDATION_REASON LIKE 'OBJECT VERSION MISMATCH%' THEN 'OBJECT VERSION MISMATCH' 
      ELSE LAST_INVALIDATION_REASON 
    END LAST_INVALIDATION_REASON,
    MAX(PLAN_MEMORY_SIZE) PLAN_MEMORY_SIZE
  FROM
    ( SELECT DISPLAY_STATEMENT_TEXT FROM BASIS_INFO ) BI,
    _SYS_STATISTICS.HOST_SQL_PLAN_CACHE C 
  GROUP BY
    HOST,
    PORT,
    SNAPSHOT_ID,
    SCHEMA_NAME,
    TABLE_LOCATIONS,
    STATEMENT_HASH,
    PLAN_ID,
    USER_NAME,
    TO_VARCHAR(ACCESSED_TABLE_NAMES),
    TO_VARCHAR(STATEMENT_STRING),
    TABLE_TYPES,
    EXECUTION_ENGINE,
    PLAN_SHARING_TYPE,
    REFERENCE_COUNT,
    SERVER_TIMESTAMP,
    IS_DISTRIBUTED_EXECUTION,
    CASE WHEN COMPILATION_OPTIONS = 'STATEMENT HINT' OR IS_PINNED_PLAN = 'TRUE' THEN 'TRUE' ELSE FALSE END,
    IS_INTERNAL,
    APPLICATION_NAME,
    APPLICATION_SOURCE,
    LAST_INVALIDATION_REASON,
    BI.DISPLAY_STATEMENT_TEXT
)
SELECT
  BEGIN_TIME SNAPSHOT_TIME,
  STATEMENT_HASH,
  PLAN_ID,
  CASE WHEN STORE LIKE 'COLUMN' THEN 'C' ELSE '' END || CASE WHEN STORE LIKE 'ROW' THEN 'R' ELSE '' END || CASE WHEN STORE = 'any' THEN 'any' ELSE '' END S,
  MAP(IS_PINNED, 'TRUE', 'X', 'any', 'any', ' ') P,
  MAP(IS_INTERNAL, 'TRUE', 'X', 'any', 'any', ' ') I,
  MAP(DISTRIBUTED, 'TRUE', 'X', 'any', 'any', ' ') D,
  CASE WHEN ENGINES LIKE '%COLUMN%' THEN 'C' ELSE '' END || CASE WHEN ENGINES LIKE '%ESX%' THEN 'E' ELSE '' END ||
    CASE WHEN ENGINES LIKE '%HEX%' THEN 'H' ELSE '' END || CASE WHEN ENGINES LIKE '%OLAP%' THEN 'O' ELSE '' END ||
    CASE WHEN ENGINES LIKE '%EXTERNAL%' THEN 'X' ELSE '' END || CASE WHEN ENGINES LIKE '%SQLSCRIPT%' THEN 'S' ELSE '' END ||
    CASE WHEN ENGINES LIKE '%ROW%' THEN 'R' ELSE '' END ENG, 
  SQL_TYPE TP,
  LPAD(RECORDS, 13) RECORDS,
  LPAD(TO_DECIMAL(REC_PER_EXEC, 10, 2), 12) AVG_RECORDS,
  LPAD(EXECUTIONS, 12) EXECUTIONS,
  LPAD(TO_DECIMAL(ROUND(EXEC_MS / 1000), 10, 0), 8) EXEC_S,
  LPAD(TO_DECIMAL(EXEC_PER_EXEC_MS, 10, 2), 11) AVG_EXEC_MS,
  LPAD(TO_DECIMAL(CUR_PER_EXEC_MS, 10, 2), 10) AVG_CUR_MS,
  LPAD(TO_DECIMAL(EXEC_PER_REC_MS, 10, 2), 10) AVG_REC_MS,
  LPAD(TO_DECIMAL(LOCK_PER_EXEC_MS, 10, 2), 11) AVG_LOCK_MS,
  LPAD(TO_DECIMAL(NW_PER_EXEC_MS, 10, 2), 9) AVG_NW_MS,
  LPAD(TO_DECIMAL(THR_PER_EXEC, 10, 2), 11) AVG_THREADS,
  LPAD(TO_DECIMAL(NW_REQ_PER_EXEC, 10, 2), 10) AVG_NW_REQ,
  LPAD(TO_DECIMAL(NW_PER_EXEC_MB, 10, 2), 9) AVG_NW_MB,
  LPAD(TO_DECIMAL(MEM_PER_EXEC_MB, 10, 2), 10) AVG_MEM_MB,
  LPAD(TO_DECIMAL(BC_IO_PER_EXEC_MB, 10, 2), 12) AVG_BC_IO_MB,
  LPAD(TO_DECIMAL(PLAN_MB, 10, 2), 10) PLAN_MB,
  LPAD(BC_MISS_COUNT, 13) BC_MISS_COUNT,
  LPAD(TO_DECIMAL(MEMORY_MB / 1024, 10, 2), 10) MEMORY_GB,
  LPAD(THREADS, 10) THREADS,
  LPAD(TO_DECIMAL(OPEN_PER_EXEC_MS, 10, 2), 11) AVG_OPEN_MS,
  LPAD(TO_DECIMAL(FETCH_PER_EXEC_MS, 10, 2), 12) AVG_FETCH_MS,
  LPAD(PREPARATIONS, 5) PREPS,
  LPAD(TO_DECIMAL(ROUND(PREP_MS), 10, 0), 10) PREP_MS,
  LPAD(TO_DECIMAL(ROUND(LOCK_WAIT_MS), 10, 0), 10) LOCK_MS,
  LPAD(TO_DECIMAL(ROUND(NW_SIZE_MB), 10, 0), 8) NW_MB,
  DB_USER,
  APP_NAME,
  APP_SOURCE,
  MAP(SHARING_TYPE, 'GLOBAL', 'G', 'SESSION EXCLUSIVE GLOBAL', 'SEG', 'SESSION LOCAL', 'SL', 'LOGICAL SESSION GLOBAL', 'LSG', 'any', 'any', SHARING_TYPE) PST,
  INV_REASON,
  LPAD(NUM, 7) CNT,
  HOST,
  PORT,
  SCHEMA_NAME,
  LOCATION,
  LPAD(REFERENCE_COUNT, 3) RC,
  TABLES,
  REPLACE(REPLACE(REPLACE(STATEMENT_STRING, CHAR(9), CHAR(32)), CHAR(10), CHAR(32)), CHAR(13), CHAR(32)) STATEMENT_STRING
FROM
( SELECT
    CASE 
      WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'TIME') != 0 THEN 
        CASE 
          WHEN TIME_AGGREGATE_BY LIKE 'TS%' THEN
            TO_VARCHAR(ADD_SECONDS(TO_TIMESTAMP('2014/01/01 00:00:00', 'YYYY/MM/DD HH24:MI:SS'), FLOOR(SECONDS_BETWEEN(TO_TIMESTAMP('2014/01/01 00:00:00', 
            'YYYY/MM/DD HH24:MI:SS'), BEGIN_TIME) / SUBSTR(TIME_AGGREGATE_BY, 3)) * SUBSTR(TIME_AGGREGATE_BY, 3)), 'YYYY/MM/DD HH24:MI:SS')
          ELSE TO_VARCHAR(BEGIN_TIME, TIME_AGGREGATE_BY)
        END
      ELSE 'any' 
    END BEGIN_TIME,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'HOST')                 != 0 THEN HOST                 ELSE MAP(BI_HOST, '%', 'any', BI_HOST)                                 END HOST,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'PORT')                 != 0 THEN TO_VARCHAR(PORT)     ELSE MAP(BI_PORT, '%', 'any', BI_PORT)                                 END PORT,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'SCHEMA')               != 0 THEN SCHEMA_NAME          ELSE MAP(BI_SCHEMA_NAME, '%', 'any', BI_SCHEMA_NAME)                   END SCHEMA_NAME,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'LOCATION')             != 0 THEN TABLE_LOCATION       ELSE MAP(BI_TABLE_LOCATION, '%', 'any', BI_TABLE_LOCATION)             END LOCATION,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'TABLES')               != 0 THEN TABLE_NAMES          ELSE 'any'                                                             END TABLES,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'DB_USER')              != 0 THEN USER_NAME            ELSE MAP(BI_DB_USER, '%', 'any', BI_DB_USER)                           END DB_USER,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'HASH')                 != 0 THEN STATEMENT_HASH       ELSE MAP(BI_STATEMENT_HASH, '%', 'any', BI_STATEMENT_HASH)             END STATEMENT_HASH,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'PLAN_ID')              != 0 THEN TO_VARCHAR(PLAN_ID)  ELSE 'any'                                                             END PLAN_ID,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'STORE')                != 0 THEN STORE                ELSE MAP(BI_STORE, '%', 'any', BI_STORE)                               END STORE,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'ENGINES')              != 0 THEN ENGINES              ELSE MAP(BI_ENGINES, '%', 'any', BI_ENGINES)                           END ENGINES,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'SHARING_TYPE')         != 0 THEN SHARING_TYPE         ELSE MAP(BI_SHARING_TYPE, '%', 'any', BI_SHARING_TYPE)                 END SHARING_TYPE,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'HASH')                 != 0 THEN STATEMENT_STRING     ELSE 'any'                                                             END STATEMENT_STRING,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'SQL_TYPE')             != 0 THEN SQL_TYPE             ELSE MAP(BI_SQL_TYPE, '%', 'any', 'DM', SQL_TYPE, BI_SQL_TYPE)         END SQL_TYPE,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'DIST')                 != 0 THEN DISTRIBUTED          ELSE MAP(BI_IS_DIST, '%', 'any', BI_IS_DIST)                           END DISTRIBUTED,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'PINNED')               != 0 THEN IS_PINNED            ELSE MAP(BI_IS_PINNED, '%', 'any', BI_IS_PINNED)                       END IS_PINNED,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'INTERNAL')             != 0 THEN IS_INTERNAL          ELSE 'any'                                                             END IS_INTERNAL,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'APP_SOURCE')           != 0 THEN APPLICATION_SOURCE   ELSE MAP(BI_APP_SOURCE, '%', 'any', BI_APP_SOURCE)                     END APP_SOURCE,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'APP_NAME')             != 0 THEN APPLICATION_NAME     ELSE MAP(BI_APP_NAME, '%', 'any', BI_APP_NAME)                         END APP_NAME,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'INV_REASON')           != 0 THEN INVALIDATION_REASON  ELSE MAP(BI_INV_REASON, '%', 'any', BI_INV_REASON)                     END INV_REASON,
    COUNT(*) NUM,
    SUM(REFERENCE_COUNT) REFERENCE_COUNT,
    SUM(EXECUTIONS) EXECUTIONS,
    SUM(RECORDS) RECORDS,
    MAP(SUM(EXECUTIONS), 0, 0, SUM(RECORDS) / SUM(EXECUTIONS)) REC_PER_EXEC,
    SUM(CURSOR_MS) CURSOR_MS,
    MAP(SUM(EXECUTIONS), 0, 0, SUM(CURSOR_MS) / SUM(EXECUTIONS)) CUR_PER_EXEC_MS,
    MAP(GREATEST(SUM(EXECUTIONS), SUM(RECORDS)), 0, 0, SUM(EXEC_MS) / GREATEST(SUM(EXECUTIONS), SUM(RECORDS))) EXEC_PER_REC_MS,
    SUM(EXEC_MS) EXEC_MS,
    MAP(SUM(EXECUTIONS), 0, 0, SUM(EXEC_MS) / SUM(EXECUTIONS)) EXEC_PER_EXEC_MS,
    SUM(PREPARATIONS) PREPARATIONS,
    SUM(PREP_MS) PREP_MS,
    SUM(OPEN_MS) OPEN_MS,
    MAP(SUM(EXECUTIONS), 0, 0, SUM(OPEN_MS) / SUM(EXECUTIONS)) OPEN_PER_EXEC_MS,
    SUM(FETCH_MS) FETCH_MS,
    MAP(SUM(EXECUTIONS), 0, 0, SUM(FETCH_MS) / SUM(EXECUTIONS)) FETCH_PER_EXEC_MS,
    SUM(LOCK_WAIT_MS) LOCK_WAIT_MS,
    MAP(SUM(EXECUTIONS), 0, 0, SUM(LOCK_WAIT_MS) / SUM(EXECUTIONS)) LOCK_PER_EXEC_MS,
    SUM(NETWORK_REQ) NETWORK_REQ,
    MAP(SUM(EXECUTIONS), 0, 0, SUM(NETWORK_REQ) / SUM(EXECUTIONS)) NW_REQ_PER_EXEC,
    SUM(NETWORK_MB) NW_SIZE_MB,
    MAP(SUM(EXECUTIONS), 0, 0, SUM(NETWORK_MB) / SUM(EXECUTIONS)) NW_PER_EXEC_MB,
    SUM(NETWORK_MS) NETWORK_MS,
    MAP(SUM(EXECUTIONS), 0, 0, SUM(NETWORK_MS) / SUM(EXECUTIONS)) NW_PER_EXEC_MS,
    SUM(BC_MISS_COUNT) BC_MISS_COUNT,
    MAP(SUM(TOTAL_BUFFER_CACHE_IO_READ_SIZE_MB), 0, 0, SUM(TOTAL_BUFFER_CACHE_IO_READ_SIZE_MB) / SUM(EXECUTIONS)) BC_IO_PER_EXEC_MB,
    SUM(TOTAL_BUFFER_CACHE_IO_READ_SIZE_MB) BC_IO_MB,
    SUM(MEMORY_MB) MEMORY_MB,
    MAP(SUM(EXECUTIONS), 0, 0, SUM(MEMORY_MB) / SUM(EXECUTIONS)) MEM_PER_EXEC_MB,
    SUM(PLAN_KB) / 1024 PLAN_MB,
    SUM(THREADS) THREADS,
    MAP(SUM(EXECUTIONS), 0, 0, SUM(THREADS) / SUM(EXECUTIONS)) THR_PER_EXEC,
    ORDER_BY
  FROM
  ( SELECT
      BEGIN_TIME,
      HOST,
      PORT,
      SCHEMA_NAME,
      TABLE_LOCATION,
      ACCESSED_TABLE_NAMES TABLE_NAMES,
      STATEMENT_HASH,
      SQL_TYPE,
      PLAN_ID,
      USER_NAME,
      STORE,
      ENGINES,
      SHARING_TYPE,
      REFERENCE_COUNT,
      IS_DISTRIBUTED_EXECUTION DISTRIBUTED,
      IS_PINNED_PLAN IS_PINNED,
      IS_INTERNAL,
      EXECUTION_COUNT EXECUTIONS,
      TOTAL_RESULT_RECORD_COUNT RECORDS,
      TOTAL_CURSOR_DURATION / 1000 CURSOR_MS,
      TOTAL_PREPARATION_TIME / 1000 PREP_MS,
      PREPARATION_COUNT PREPARATIONS,
      TOTAL_EXECUTION_TIME / 1000 EXEC_MS,
      TOTAL_EXECUTION_OPEN_TIME / 1000 OPEN_MS,
      TOTAL_EXECUTION_FETCH_TIME / 1000 FETCH_MS,
      TOTAL_LOCK_WAIT_DURATION / 1000 LOCK_WAIT_MS,
      TOTAL_SERVICE_NETWORK_REQUEST_COUNT NETWORK_REQ,
      TOTAL_SERVICE_NETWORK_REQUEST_SIZE / 1024 / 1024 NETWORK_MB,
      TOTAL_SERVICE_NETWORK_REQUEST_DURATION / 1000 NETWORK_MS,
      TOTAL_BUFFER_CACHE_PAGE_MISS_COUNT BC_MISS_COUNT,
      TOTAL_BUFFER_CACHE_IO_READ_SIZE / 1024/ 1024 TOTAL_BUFFER_CACHE_IO_READ_SIZE_MB,
      TOTAL_EXECUTION_MEMORY_SIZE / 1024 / 1024 MEMORY_MB,
      PLAN_MEMORY_SIZE / 1024 PLAN_KB,
      TOTAL_CALLED_THREAD_COUNT THREADS,
      APPLICATION_SOURCE,
      APPLICATION_NAME,
      LAST_INVALIDATION_REASON INVALIDATION_REASON,
      STATEMENT_STRING,
      REPLACE(UPPER(LTRIM(MAP(SUBSTR(TO_VARCHAR(STATEMENT_STRING), 1, 2), '/*', SUBSTR(TO_VARCHAR(STATEMENT_STRING), LOCATE(TO_VARCHAR(STATEMENT_STRING), '*/') + 2), TO_VARCHAR(STATEMENT_STRING)), ' ({')), CHAR(10), '') STATEMENT_STRING_CLEANED,
      AGGREGATE_BY,
      TIME_AGGREGATE_BY,
      ORDER_BY,
      BI_HOST,
      BI_PORT,
      BI_SCHEMA_NAME,
      BI_TABLE_LOCATION,
      BI_DB_USER,
      BI_APP_NAME,
      BI_APP_SOURCE,
      BI_INV_REASON,
      BI_IS_PINNED,
      BI_STATEMENT_HASH,
      BI_SQL_TYPE,
      BI_IS_DIST,
      BI_SHARING_TYPE,
      BI_STORE,
      BI_ENGINES
    FROM
    ( SELECT
        C.*,
        MAP(BI.TIMESTAMP_TYPE, 
          'SERVER', CASE BI.TIMEZONE WHEN 'UTC' THEN ADD_SECONDS(C.SERVER_TIMESTAMP, SECONDS_BETWEEN(CURRENT_TIMESTAMP, CURRENT_UTCTIMESTAMP)) ELSE 
            C.SERVER_TIMESTAMP END, 
          'EXEC', CASE BI.TIMEZONE WHEN 'UTC' THEN ADD_SECONDS(C.LAST_EXECUTION_TIMESTAMP, SECONDS_BETWEEN(CURRENT_TIMESTAMP, CURRENT_UTCTIMESTAMP)) 
            ELSE C.LAST_EXECUTION_TIMESTAMP END, 
          'PREP', CASE BI.TIMEZONE WHEN 'UTC' THEN ADD_SECONDS(C.LAST_PREPARATION_TIMESTAMP, SECONDS_BETWEEN(CURRENT_TIMESTAMP, CURRENT_UTCTIMESTAMP)) 
            ELSE C.LAST_PREPARATION_TIMESTAMP END) BEGIN_TIME,
        BI.AGGREGATE_BY,
        BI.TIME_AGGREGATE_BY,
        BI.ORDER_BY,
        BI.HOST BI_HOST,
        BI.PORT BI_PORT,
        BI.SCHEMA_NAME BI_SCHEMA_NAME,
        BI.TABLE_LOCATION BI_TABLE_LOCATION,
        BI.DB_USER BI_DB_USER,
        BI.APP_NAME BI_APP_NAME,
        BI.APP_SOURCE BI_APP_SOURCE,
        BI.INV_REASON BI_INV_REASON,
        BI.STATEMENT_HASH BI_STATEMENT_HASH,
        BI.SQL_TYPE BI_SQL_TYPE,
        BI.IS_DISTRIBUTED_EXECUTION BI_IS_DIST,
        BI.IS_PINNED_PLAN BI_IS_PINNED,
        BI.SHARING_TYPE BI_SHARING_TYPE,
        BI.STORE BI_STORE,
        BI.ENGINES BI_ENGINES
      FROM
        BASIS_INFO BI,
      ( SELECT
          DATA_SOURCE,
          HOST,
          PORT,
          SNAPSHOT_ID,
          SCHEMA_NAME,
          STATEMENT_HASH,
          PLAN_ID,
          USER_NAME,
          ACCESSED_TABLE_NAMES,
          STATEMENT_STRING,
          CASE
            WHEN STATEMENT_STRING_CLEANED LIKE 'ALTER INDEX%'       THEN 'AI'
            WHEN STATEMENT_STRING_CLEANED LIKE 'ALTER SYSTEM%'      THEN 'AS'
            WHEN STATEMENT_STRING_CLEANED LIKE 'ALTER TABLE%'       THEN 'AT'
            WHEN STATEMENT_STRING_CLEANED LIKE 'ALTER%'             THEN 'AL'
            WHEN STATEMENT_STRING_CLEANED LIKE 'CALL%'              THEN 'CA'
            WHEN STATEMENT_STRING_CLEANED LIKE 'COMMIT%'            THEN 'CO'
            WHEN STATEMENT_STRING_CLEANED LIKE 'CREATE INDEX%'      THEN 'CI'
            WHEN STATEMENT_STRING_CLEANED LIKE 'CREATE TABLE%'      THEN 'CT'
            WHEN STATEMENT_STRING_CLEANED LIKE 'CREATE%'            THEN 'CR'
            WHEN STATEMENT_STRING_CLEANED LIKE 'DELETE%'            THEN 'DE'
            WHEN STATEMENT_STRING_CLEANED LIKE 'DROP INDEX%'        THEN 'DI'
            WHEN STATEMENT_STRING_CLEANED LIKE 'DROP TABLE%'        THEN 'DT'
            WHEN STATEMENT_STRING_CLEANED LIKE 'DROP%'              THEN 'DR'
            WHEN STATEMENT_STRING_CLEANED LIKE 'EXECUTE%'           THEN 'EX'
            WHEN STATEMENT_STRING_CLEANED LIKE 'INSERT%'            THEN 'IN'
            WHEN STATEMENT_STRING_CLEANED LIKE 'MERGE%'             THEN 'ME'
            WHEN STATEMENT_STRING_CLEANED LIKE 'REPLACE%'           THEN 'RE'
            WHEN STATEMENT_STRING_CLEANED LIKE 'ROLLBACK%'          THEN 'RO'
            WHEN STATEMENT_STRING_CLEANED LIKE 'SELECT%FOR UPDATE%' THEN 'SU'
            WHEN STATEMENT_STRING_CLEANED LIKE 'SELECT%'            THEN 'SE'
            WHEN STATEMENT_STRING_CLEANED LIKE 'TRUNCATE%'          THEN 'TR'
            WHEN STATEMENT_STRING_CLEANED LIKE 'UPDATE%'            THEN 'UP'
            WHEN STATEMENT_STRING_CLEANED LIKE 'UPSERT%'            THEN 'US'
            WHEN STATEMENT_STRING_CLEANED LIKE 'WITH%'              THEN 'WI'
            ELSE 'unknown'
          END SQL_TYPE,
          STORE,
          ENGINES,
          SHARING_TYPE,
          MAX(REFERENCE_COUNT) REFERENCE_COUNT,
          SERVER_TIMESTAMP,
          IS_DISTRIBUTED_EXECUTION,
          IS_PINNED_PLAN,
          IS_INTERNAL,
          MAX(EXECUTION_COUNT) EXECUTION_COUNT,
          MAX(TOTAL_RESULT_RECORD_COUNT) TOTAL_RESULT_RECORD_COUNT,
          MAX(TOTAL_CURSOR_DURATION) TOTAL_CURSOR_DURATION,
          MAX(TOTAL_EXECUTION_TIME) TOTAL_EXECUTION_TIME,
          MAX(TOTAL_EXECUTION_OPEN_TIME) TOTAL_EXECUTION_OPEN_TIME,
          MAX(TOTAL_EXECUTION_FETCH_TIME) TOTAL_EXECUTION_FETCH_TIME,
          MAX(TOTAL_PREPARATION_TIME) TOTAL_PREPARATION_TIME,
          MAX(PREPARATION_COUNT) PREPARATION_COUNT,
          MAX(TOTAL_LOCK_WAIT_DURATION) TOTAL_LOCK_WAIT_DURATION,
          MAX(LAST_PREPARATION_TIMESTAMP) LAST_PREPARATION_TIMESTAMP,
          MAX(LAST_EXECUTION_TIMESTAMP) LAST_EXECUTION_TIMESTAMP,
          MAX(TOTAL_SERVICE_NETWORK_REQUEST_COUNT) TOTAL_SERVICE_NETWORK_REQUEST_COUNT,
          MAX(TOTAL_SERVICE_NETWORK_REQUEST_DURATION) TOTAL_SERVICE_NETWORK_REQUEST_DURATION,
          MAX(TOTAL_BUFFER_CACHE_PAGE_MISS_COUNT) TOTAL_BUFFER_CACHE_PAGE_MISS_COUNT,
          MAX(TOTAL_BUFFER_CACHE_IO_READ_SIZE) TOTAL_BUFFER_CACHE_IO_READ_SIZE,
          MAX(TOTAL_SERVICE_NETWORK_REQUEST_SIZE) TOTAL_SERVICE_NETWORK_REQUEST_SIZE,
          MAX(TOTAL_CALLED_THREAD_COUNT) TOTAL_CALLED_THREAD_COUNT,
          MAX(TOTAL_EXECUTION_MEMORY_SIZE) TOTAL_EXECUTION_MEMORY_SIZE,
          TABLE_LOCATION,
          MAX(APPLICATION_SOURCE) APPLICATION_SOURCE,
          MAX(APPLICATION_NAME) APPLICATION_NAME,
          MAX(LAST_INVALIDATION_REASON) LAST_INVALIDATION_REASON,
          MAX(PLAN_MEMORY_SIZE) PLAN_MEMORY_SIZE
        FROM
          SQL_CACHE C
        GROUP BY
          DATA_SOURCE,
          HOST,
          PORT,
          SNAPSHOT_ID,
          SCHEMA_NAME,
          TABLE_LOCATION,
          STATEMENT_HASH,
          PLAN_ID,
          USER_NAME,
          ACCESSED_TABLE_NAMES,
          STATEMENT_STRING,
          STATEMENT_STRING_CLEANED,
          STORE,
          ENGINES,
          SHARING_TYPE,
          SERVER_TIMESTAMP,
          IS_DISTRIBUTED_EXECUTION,
          IS_PINNED_PLAN,
          IS_INTERNAL
      ) C
      WHERE
        C.HOST LIKE BI.HOST AND
        TO_VARCHAR(C.PORT) LIKE BI.PORT AND
        C.SCHEMA_NAME LIKE BI.SCHEMA_NAME AND
        C.STATEMENT_HASH LIKE BI.STATEMENT_HASH AND
        ( BI.TIMESTAMP_TYPE = 'SERVER' AND IFNULL(CASE BI.TIMEZONE WHEN 'UTC' THEN ADD_SECONDS(C.SERVER_TIMESTAMP, SECONDS_BETWEEN(CURRENT_TIMESTAMP, CURRENT_UTCTIMESTAMP)) 
            ELSE C.SERVER_TIMESTAMP END, TO_TIMESTAMP('2000/01/01 00:00:00', 'YYYY/MM/DD HH24:MI:SS')) BETWEEN BI.BEGIN_TIME AND BI.END_TIME OR
          BI.TIMESTAMP_TYPE = 'EXEC'   AND IFNULL(CASE BI.TIMEZONE WHEN 'UTC' THEN ADD_SECONDS(C.LAST_EXECUTION_TIMESTAMP, SECONDS_BETWEEN(CURRENT_TIMESTAMP, CURRENT_UTCTIMESTAMP)) 
            ELSE C.LAST_EXECUTION_TIMESTAMP END, TO_TIMESTAMP('2000/01/01 00:00:00', 'YYYY/MM/DD HH24:MI:SS')) BETWEEN BI.BEGIN_TIME AND BI.END_TIME OR
          BI.TIMESTAMP_TYPE = 'PREP'   AND IFNULL(CASE BI.TIMEZONE WHEN 'UTC' THEN ADD_SECONDS(C.LAST_PREPARATION_TIMESTAMP, SECONDS_BETWEEN(CURRENT_TIMESTAMP, CURRENT_UTCTIMESTAMP)) 
            ELSE C.LAST_PREPARATION_TIMESTAMP END, TO_TIMESTAMP('2000/01/01 00:00:00', 'YYYY/MM/DD HH24:MI:SS')) BETWEEN BI.BEGIN_TIME AND BI.END_TIME ) AND
        ( BI.TABLE_NAME = '%' OR C.ACCESSED_TABLE_NAMES LIKE '%.' || BI.TABLE_NAME || '(%' ) AND
        C.SHARING_TYPE LIKE BI.SHARING_TYPE AND
        UPPER(C.STATEMENT_STRING) LIKE UPPER(BI.SQL_PATTERN) AND
        ( BI.SQL_TYPE = 'DM' AND C.SQL_TYPE IN ('DE', 'IN', 'ME', 'SU', 'UP', 'US' ) OR
          C.SQL_TYPE LIKE BI.SQL_TYPE
        ) AND
        IFNULL(C.USER_NAME, '') LIKE BI.DB_USER AND
        IFNULL(C.APPLICATION_SOURCE, '') LIKE BI.APP_SOURCE AND
        IFNULL(C.APPLICATION_NAME, '') LIKE BI.APP_NAME AND
        IFNULL(C.LAST_INVALIDATION_REASON, '') LIKE BI.INV_REASON AND
        C.DATA_SOURCE = BI.DATA_SOURCE AND
        C.IS_DISTRIBUTED_EXECUTION LIKE BI.IS_DISTRIBUTED_EXECUTION AND
        C.IS_PINNED_PLAN LIKE BI.IS_PINNED_PLAN AND
        ( BI.EXCLUDE_CURRENT_RANGE_RESTRICTION = ' ' OR UPPER(C.STATEMENT_STRING) NOT LIKE '%WITH RANGE_RESTRICTION(_CURRENT_)' ) AND
        ( BI.IS_INTERNAL = '%' OR BI.IS_INTERNAL = 'X' AND C.IS_INTERNAL = 'TRUE' OR BI.IS_INTERNAL = ' ' AND C.IS_INTERNAL = 'FALSE' ) AND
        IFNULL(C.STORE, '') LIKE BI.STORE AND
        IFNULL(C.ENGINES, '') LIKE BI.ENGINES AND
        ( BI.MIN_PLAN_SIZE_KB = -1 OR C.PLAN_MEMORY_SIZE / 1024 >= BI.MIN_PLAN_SIZE_KB ) AND
        C.TABLE_LOCATION LIKE BI.TABLE_LOCATION AND
        ( BI.ONLY_CROSS_NODE_JOINS = ' ' OR C.TABLE_LOCATION LIKE '%),%' )
    )
  )
  GROUP BY
    CASE 
      WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'TIME') != 0 THEN 
        CASE 
          WHEN TIME_AGGREGATE_BY LIKE 'TS%' THEN
            TO_VARCHAR(ADD_SECONDS(TO_TIMESTAMP('2014/01/01 00:00:00', 'YYYY/MM/DD HH24:MI:SS'), FLOOR(SECONDS_BETWEEN(TO_TIMESTAMP('2014/01/01 00:00:00', 
            'YYYY/MM/DD HH24:MI:SS'), BEGIN_TIME) / SUBSTR(TIME_AGGREGATE_BY, 3)) * SUBSTR(TIME_AGGREGATE_BY, 3)), 'YYYY/MM/DD HH24:MI:SS')
          ELSE TO_VARCHAR(BEGIN_TIME, TIME_AGGREGATE_BY)
        END
      ELSE 'any' 
    END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'HOST')                 != 0 THEN HOST                 ELSE MAP(BI_HOST, '%', 'any', BI_HOST)                                 END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'PORT')                 != 0 THEN TO_VARCHAR(PORT)     ELSE MAP(BI_PORT, '%', 'any', BI_PORT)                                 END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'SCHEMA')               != 0 THEN SCHEMA_NAME          ELSE MAP(BI_SCHEMA_NAME, '%', 'any', BI_SCHEMA_NAME)                   END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'LOCATION')             != 0 THEN TABLE_LOCATION       ELSE MAP(BI_TABLE_LOCATION, '%', 'any', BI_TABLE_LOCATION)             END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'TABLES')               != 0 THEN TABLE_NAMES          ELSE 'any'                                                             END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'DB_USER')              != 0 THEN USER_NAME            ELSE MAP(BI_DB_USER, '%', 'any', BI_DB_USER)                           END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'HASH')                 != 0 THEN STATEMENT_HASH       ELSE MAP(BI_STATEMENT_HASH, '%', 'any', BI_STATEMENT_HASH)             END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'PLAN_ID')              != 0 THEN TO_VARCHAR(PLAN_ID)  ELSE 'any'                                                             END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'STORE')                != 0 THEN STORE                ELSE MAP(BI_STORE, '%', 'any', BI_STORE)                               END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'ENGINES')              != 0 THEN ENGINES              ELSE MAP(BI_ENGINES, '%', 'any', BI_ENGINES)                           END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'SHARING_TYPE')         != 0 THEN SHARING_TYPE         ELSE MAP(BI_SHARING_TYPE, '%', 'any', BI_SHARING_TYPE)                 END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'HASH')                 != 0 THEN STATEMENT_STRING     ELSE 'any'                                                             END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'SQL_TYPE')             != 0 THEN SQL_TYPE             ELSE MAP(BI_SQL_TYPE, '%', 'any', 'DM', SQL_TYPE, BI_SQL_TYPE)         END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'DIST')                 != 0 THEN DISTRIBUTED          ELSE MAP(BI_IS_DIST, '%', 'any', BI_IS_DIST)                           END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'PINNED')               != 0 THEN IS_PINNED            ELSE MAP(BI_IS_PINNED, '%', 'any', BI_IS_PINNED)                       END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'INTERNAL')             != 0 THEN IS_INTERNAL          ELSE 'any'                                                             END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'APP_SOURCE')           != 0 THEN APPLICATION_SOURCE   ELSE MAP(BI_APP_SOURCE, '%', 'any', BI_APP_SOURCE)                     END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'APP_NAME')             != 0 THEN APPLICATION_NAME     ELSE MAP(BI_APP_NAME, '%', 'any', BI_APP_NAME)                         END,
    CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'INV_REASON')           != 0 THEN INVALIDATION_REASON  ELSE MAP(BI_INV_REASON, '%', 'any', BI_INV_REASON)                     END,
    ORDER_BY
)
ORDER BY 
  MAP(ORDER_BY, 'EXEC', EXEC_MS, 'PREP', PREP_MS, 'CURSOR', CURSOR_MS, 'OPEN', OPEN_MS, 'FETCH', FETCH_MS, 'LOCK', LOCK_WAIT_MS,
    'EXECUTIONS', EXECUTIONS, 'RECORDS', RECORDS, 'NETWORK_COUNT', NETWORK_REQ, 'NETWORK_SIZE', NW_SIZE_MB, 'NETWORK_TIME', NETWORK_MS,
    'BC_MISS_COUNT', BC_MISS_COUNT, 'BC_IO_SIZE', BC_IO_MB, 'MEMORY', MEMORY_MB, 'MEM_PER_EXEC', MEM_PER_EXEC_MB,
    'PLAN_MEM', PLAN_MB, 'THREAD', THREADS) DESC,
  MAP(ORDER_BY, 'TIME', BEGIN_TIME) DESC,
  BEGIN_TIME DESC
WITH HINT (IGNORE_PLAN_CACHE)      
    `;

    const result = await executeQuery(query);
    return formatQueryResult(result);
  } catch (error) {
    return createErrorResponse(`조회 실패: ${error instanceof Error ? error.message : String(error)}`);
  }
}
