import { executeQuery, formatQueryResult, createErrorResponse, ToolResponse } from '../lib/utils';

export type TimeAggregateBy = 'NONE' | 'HOUR' | 'DAY' | 'HOUR_OF_DAY';

export interface LoadHistory {
  beginTime?: string;
  endTime?: string;
  timeAggregateBy?: TimeAggregateBy;
}

export async function handleLoadHistory(params: LoadHistory): Promise<ToolResponse> {
  try {
    // Extract and sanitize parameters
    const {
      beginTime = 'C-H1',  // Default: 1 hour ago
      endTime = 'C',       // Default: current time
      timeAggregateBy = 'NONE'  // Default: no time aggregation
    } = params;

    // timeAggregateBy 값이 허용된 값 중 하나인지 체크
    const allowedTimeAggregates: TimeAggregateBy[] = ['NONE', 'HOUR', 'DAY', 'HOUR_OF_DAY'];
    const safeTimeAggregateBy: TimeAggregateBy = allowedTimeAggregates.includes(timeAggregateBy as TimeAggregateBy)
      ? (timeAggregateBy as TimeAggregateBy)
      : 'NONE';

    // 파라미터를 명확하게 문자열로 변환하고 undefined/null 방지
    const safeBeginTime = beginTime != null ? String(beginTime) : 'C-H1';
    const safeEndTime = endTime != null ? String(endTime) : 'C';

    const query = `
SELECT
  SAMPLE_TIME SNAPSHOT_TIME,
  IFNULL(LPAD(SITE_ID, 2), '') ST,
  HOST,
  LPAD(PORT, 5) PORT,
  LPAD(TO_DECIMAL(ROUND(PING_MS), 10, 0), 5) P_MS,
  LPAD(TO_DECIMAL(CPU_PCT, 10, 2), 5) CPU,
  LPAD(TO_DECIMAL(SYS_CPU_PCT, 10, 2), 5) SYS, 
  LPAD(TO_DECIMAL(USED_MEM_GB, 10, 2), 8) USED_GB,
  LPAD(TO_DECIMAL(ROUND(CONNECTIONS), 10, 0), 5) CONNS,
  LPAD(TO_DECIMAL(ROUND(TRANSACTIONS), 10, 0), 5) TRANS,
  LPAD(TO_DECIMAL(BLOCKED_TRANSACTIONS, 10, 2), 6) BTRANS,
  LPAD(TO_DECIMAL(ROUND(EXECUTIONS / INTERVAL_S), 10, 0), 7) STMT_PS,
  LPAD(TO_DECIMAL(ACTIVE_THREADS, 10, 2), 7) ACT_THR,
  LPAD(TO_DECIMAL(WAITING_THREADS, 10, 2), 8) WAIT_THR,
  LPAD(TO_DECIMAL(ACTIVE_SQL_EXECUTORS, 10, 2), 7) ACT_SQL,
  LPAD(TO_DECIMAL(WAITING_SQL_EXECUTORS, 10, 2), 8) WAIT_SQL,
  LPAD(TO_DECIMAL(PENDING_SESSIONS, 10, 2), 9) PEND_SESS,
  LPAD(TO_DECIMAL(ROUND(VERSIONS), 10, 0), 10) VERSIONS,
  LPAD(TO_DECIMAL(ROUND(COMMIT_ID_RANGE), 10, 0), 9) COM_RANGE,
  LPAD(TO_DECIMAL(ROUND(HANDLES), 10, 0), 7) HANDLES,
  LPAD(TO_DECIMAL(ROUND(MERGES), 10, 0), 6) MERGES,
  LPAD(TO_DECIMAL(ROUND(UNLOADS), 10, 0), 7) UNLOADS,
  LPAD(TO_DECIMAL(SWAP_IN_MB, 10, 2), 7) SWAP_MB,
  LPAD(TO_DECIMAL(ROUND(ADMISSION_CONTROL_ADMITS / INTERVAL_S), 10, 0), 7) AC_AC,
  LPAD(TO_DECIMAL(ROUND(ADMISSION_CONTROL_REJECTS / INTERVAL_S), 10, 0), 7) AC_RC,
  LPAD(TO_DECIMAL(ADMISSION_CONTROL_QUEUE_SIZE, 10, 2), 7) AC_QS,
  LPAD(TO_DECIMAL(ADMISSION_CONTROL_WAIT_TIME / 1000000 / INTERVAL_S, 10, 2), 7) AC_WT
FROM
( SELECT
    CASE 
      WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'TIME') != 0 THEN 
        CASE 
          WHEN TIME_AGGREGATE_BY LIKE 'TS%' THEN
            TO_VARCHAR(ADD_SECONDS(TO_TIMESTAMP('2014/01/01 00:00:00', 'YYYY/MM/DD HH24:MI:SS'), FLOOR(SECONDS_BETWEEN(TO_TIMESTAMP('2014/01/01 00:00:00', 
            'YYYY/MM/DD HH24:MI:SS'), CASE TIMEZONE WHEN 'UTC' THEN ADD_SECONDS(SAMPLE_TIME, SECONDS_BETWEEN(CURRENT_TIMESTAMP, CURRENT_UTCTIMESTAMP)) ELSE SAMPLE_TIME END) / SUBSTR(TIME_AGGREGATE_BY, 3)) * SUBSTR(TIME_AGGREGATE_BY, 3)), 'YYYY/MM/DD HH24:MI:SS')
          ELSE TO_VARCHAR(CASE TIMEZONE WHEN 'UTC' THEN ADD_SECONDS(SAMPLE_TIME, SECONDS_BETWEEN(CURRENT_TIMESTAMP, CURRENT_UTCTIMESTAMP)) ELSE SAMPLE_TIME END, TIME_AGGREGATE_BY)
        END
      ELSE 'any' 
    END SAMPLE_TIME,
    HOST,
    SITE_ID,
    TO_VARCHAR(PORT) PORT,
    AVG(PING_MS) PING_MS,
    AVG(CPU_PCT) CPU_PCT,
    AVG(SYS_CPU_PCT) SYS_CPU_PCT,
    AVG(USED_MEM_GB) USED_MEM_GB,
    AVG(SWAP_IN_MB) SWAP_IN_MB,
    AVG(CONNECTIONS) CONNECTIONS,
    AVG(TRANSACTIONS) TRANSACTIONS,
    AVG(BLOCKED_TRANSACTIONS) BLOCKED_TRANSACTIONS,
    SUM(EXECUTIONS) EXECUTIONS,
    AVG(COMMIT_ID_RANGE) COMMIT_ID_RANGE,
    AVG(VERSIONS) VERSIONS,
    AVG(PENDING_SESSIONS) PENDING_SESSIONS,
    AVG(RECORD_LOCKS) RECORD_LOCKS,
    AVG(ACTIVE_THREADS) ACTIVE_THREADS,
    AVG(ACTIVE_SQL_EXECUTORS) ACTIVE_SQL_EXECUTORS,
    AVG(WAITING_THREADS) WAITING_THREADS,
    AVG(WAITING_SQL_EXECUTORS) WAITING_SQL_EXECUTORS,
    SUM(MERGES) MERGES,
    SUM(UNLOADS) UNLOADS,
    AVG(HANDLES) HANDLES,
    SUM(ADMISSION_CONTROL_ADMITS) ADMISSION_CONTROL_ADMITS,
    SUM(ADMISSION_CONTROL_REJECTS) ADMISSION_CONTROL_REJECTS,
    AVG(ADMISSION_CONTROL_QUEUE_SIZE) ADMISSION_CONTROL_QUEUE_SIZE,
    SUM(ADMISSION_CONTROL_WAIT_TIME) ADMISSION_CONTROL_WAIT_TIME,
    SUM(INTERVAL_S) INTERVAL_S,
    MIN_CPU_PCT,
    MIN_SYS_CPU_PCT,
    MIN_VERSIONS,
    MIN_PING_MS,
    MIN_HANDLES,
    MIN_REJECTIONS_PER_S,
    MIN_QUEUE_SIZE
  FROM
  ( SELECT
      SAMPLE_TIME,
      CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'SITE_ID') != 0 THEN TO_VARCHAR(SITE_ID) ELSE MAP(BI_SITE_ID, -1, 'any', TO_VARCHAR(BI_SITE_ID)) END SITE_ID,
      CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'HOST') != 0 THEN HOST ELSE MAP(BI_HOST, '%', 'any', BI_HOST) END HOST,
      PORT,
      AVG(PING_MS) PING_MS,
      AVG(CPU_PCT) CPU_PCT,
      AVG(SYS_CPU_PCT) SYS_CPU_PCT,
      AVG(USED_MEM_GB) USED_MEM_GB,
      AVG(SWAP_IN_MB) SWAP_IN_MB,
      SUM(CONNECTIONS) CONNECTIONS,
      SUM(TRANSACTIONS) TRANSACTIONS,
      SUM(BLOCKED_TRANSACTIONS) BLOCKED_TRANSACTIONS,
      SUM(EXECUTIONS) EXECUTIONS,
      MAX(COMMIT_ID_RANGE) COMMIT_ID_RANGE,
      SUM(VERSIONS) VERSIONS,
      SUM(PENDING_SESSIONS) PENDING_SESSIONS,
      SUM(RECORD_LOCKS) RECORD_LOCKS,
      SUM(ACTIVE_THREADS) ACTIVE_THREADS,
      SUM(ACTIVE_SQL_EXECUTORS) ACTIVE_SQL_EXECUTORS,
      SUM(WAITING_THREADS) WAITING_THREADS,
      SUM(WAITING_SQL_EXECUTORS) WAITING_SQL_EXECUTORS,
      SUM(MERGES) MERGES,
      SUM(UNLOADS) UNLOADS,
      SUM(HANDLES) HANDLES,
      SUM(ADMISSION_CONTROL_ADMITS) ADMISSION_CONTROL_ADMITS,
      SUM(ADMISSION_CONTROL_REJECTS) ADMISSION_CONTROL_REJECTS,
      SUM(ADMISSION_CONTROL_QUEUE_SIZE) ADMISSION_CONTROL_QUEUE_SIZE,
      SUM(ADMISSION_CONTROL_WAIT_TIME) ADMISSION_CONTROL_WAIT_TIME,
      AVG(INTERVAL_S) INTERVAL_S,
      MIN_CPU_PCT,
      MIN_SYS_CPU_PCT,
      MIN_VERSIONS,
      MIN_PING_MS,
      MIN_HANDLES,
      MIN_REJECTIONS_PER_S,
      MIN_QUEUE_SIZE,
      TIMEZONE,
      AGGREGATE_BY,
      TIME_AGGREGATE_BY
    FROM
    ( SELECT
        L.TIME SAMPLE_TIME,
        L.SITE_ID,
        L.HOST,
        CASE WHEN BI.AGGREGATE_BY = 'NONE' OR INSTR(BI.AGGREGATE_BY, 'PORT') != 0 THEN TO_VARCHAR(L.PORT) ELSE MAP(BI.PORT, '%', 'any', BI.PORT) END PORT,
        SUM(L.PING_TIME) PING_MS,
        SUM(L.CPU) CPU_PCT,
        SUM(L.SYSTEM_CPU) SYS_CPU_PCT,
        SUM(L.MEMORY_USED) / 1024 / 1024 / 1024 USED_MEM_GB,
        SUM(L.SWAP_IN) / 1024 / 1024 SWAP_IN_MB,
        SUM(L.CONNECTIONS) CONNECTIONS,
        SUM(L.TRANSACTIONS) TRANSACTIONS,
        SUM(L.BLOCKED_TRANSACTIONS) BLOCKED_TRANSACTIONS,
        SUM(L.STATEMENTS) EXECUTIONS,
        MAX(L.COMMIT_ID_RANGE) COMMIT_ID_RANGE,
        SUM(L.VERSIONS) VERSIONS,
        SUM(L.PENDING_SESSIONS) PENDING_SESSIONS,
        SUM(L.RECORD_LOCKS) RECORD_LOCKS,
        SUM(L.ACTIVE_THREADS) ACTIVE_THREADS,
        SUM(L.ACTIVE_SQL_EXECUTORS) ACTIVE_SQL_EXECUTORS,
        SUM(L.WAITING_THREADS) WAITING_THREADS,
        SUM(L.WAITING_SQL_EXECUTORS) WAITING_SQL_EXECUTORS,
        SUM(L.MERGES) MERGES,
        SUM(L.UNLOADS) UNLOADS,
        SUM(L.HANDLES) HANDLES,
        SUM(ADMISSION_CONTROL_ADMITS) ADMISSION_CONTROL_ADMITS,
        SUM(ADMISSION_CONTROL_REJECTS) ADMISSION_CONTROL_REJECTS,
        SUM(ADMISSION_CONTROL_QUEUE_SIZE) ADMISSION_CONTROL_QUEUE_SIZE,
        SUM(ADMISSION_CONTROL_WAIT_TIME) ADMISSION_CONTROL_WAIT_TIME,
        AVG(INTERVAL_S) INTERVAL_S,
        BI.SITE_ID BI_SITE_ID,
        BI.HOST BI_HOST,
        BI.MIN_CPU_PCT,
        BI.MIN_SYS_CPU_PCT,
        BI.MIN_VERSIONS,
        BI.MIN_PING_MS,
        BI.MIN_HANDLES,
        BI.MIN_REJECTIONS_PER_S,
        BI.MIN_QUEUE_SIZE,
        BI.TIMEZONE,
        BI.AGGREGATE_BY,
        BI.TIME_AGGREGATE_BY
      FROM
      ( SELECT
          CASE
            WHEN BEGIN_TIME =    'C'                             THEN CURRENT_TIMESTAMP
            WHEN BEGIN_TIME LIKE 'C-S%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(BEGIN_TIME, 'C-S'))
            WHEN BEGIN_TIME LIKE 'C-M%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(BEGIN_TIME, 'C-M') * 60)
            WHEN BEGIN_TIME LIKE 'C-H%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(BEGIN_TIME, 'C-H') * 3600)
            WHEN BEGIN_TIME LIKE 'C-D%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(BEGIN_TIME, 'C-D') * 86400)
            WHEN BEGIN_TIME LIKE 'C-W%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(BEGIN_TIME, 'C-W') * 86400 * 7)
            WHEN BEGIN_TIME LIKE 'E-S%'                          THEN ADD_SECONDS(TO_TIMESTAMP(END_TIME, 'YYYY/MM/DD HH24:MI:SS'), -SUBSTR_AFTER(BEGIN_TIME, 'E-S'))
            WHEN BEGIN_TIME LIKE 'E-M%'                          THEN ADD_SECONDS(TO_TIMESTAMP(END_TIME, 'YYYY/MM/DD HH24:MI:SS'), -SUBSTR_AFTER(BEGIN_TIME, 'E-M') * 60)
            WHEN BEGIN_TIME LIKE 'E-H%'                          THEN ADD_SECONDS(TO_TIMESTAMP(END_TIME, 'YYYY/MM/DD HH24:MI:SS'), -SUBSTR_AFTER(BEGIN_TIME, 'E-H') * 3600)
            WHEN BEGIN_TIME LIKE 'E-D%'                          THEN ADD_SECONDS(TO_TIMESTAMP(END_TIME, 'YYYY/MM/DD HH24:MI:SS'), -SUBSTR_AFTER(BEGIN_TIME, 'E-D') * 86400)
            WHEN BEGIN_TIME LIKE 'E-W%'                          THEN ADD_SECONDS(TO_TIMESTAMP(END_TIME, 'YYYY/MM/DD HH24:MI:SS'), -SUBSTR_AFTER(BEGIN_TIME, 'E-W') * 86400 * 7)
            WHEN BEGIN_TIME =    'MIN'                           THEN TO_TIMESTAMP('1000/01/01 00:00:00', 'YYYY/MM/DD HH24:MI:SS')
            WHEN BEGIN_TIME LIKE '____/__/__'                    THEN TO_TIMESTAMP(BEGIN_TIME || CHAR(32) || '00:00:00', 'YYYY/MM/DD HH24:MI:SS')
            WHEN SUBSTR(BEGIN_TIME, 1, 1) NOT IN ('C', 'E', 'M') THEN TO_TIMESTAMP(BEGIN_TIME, 'YYYY/MM/DD HH24:MI:SS')
          END BEGIN_TIME,
          CASE
            WHEN END_TIME =    'C'                             THEN CURRENT_TIMESTAMP
            WHEN END_TIME LIKE 'C-S%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(END_TIME, 'C-S'))
            WHEN END_TIME LIKE 'C-M%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(END_TIME, 'C-M') * 60)
            WHEN END_TIME LIKE 'C-H%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(END_TIME, 'C-H') * 3600)
            WHEN END_TIME LIKE 'C-D%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(END_TIME, 'C-D') * 86400)
            WHEN END_TIME LIKE 'C-W%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(END_TIME, 'C-W') * 86400 * 7)
            WHEN END_TIME LIKE 'B+S%'                          THEN ADD_SECONDS(TO_TIMESTAMP(BEGIN_TIME, 'YYYY/MM/DD HH24:MI:SS'), SUBSTR_AFTER(END_TIME, 'B+S'))
            WHEN END_TIME LIKE 'B+M%'                          THEN ADD_SECONDS(TO_TIMESTAMP(BEGIN_TIME, 'YYYY/MM/DD HH24:MI:SS'), SUBSTR_AFTER(END_TIME, 'B+M') * 60)
            WHEN END_TIME LIKE 'B+H%'                          THEN ADD_SECONDS(TO_TIMESTAMP(BEGIN_TIME, 'YYYY/MM/DD HH24:MI:SS'), SUBSTR_AFTER(END_TIME, 'B+H') * 3600)
            WHEN END_TIME LIKE 'B+D%'                          THEN ADD_SECONDS(TO_TIMESTAMP(BEGIN_TIME, 'YYYY/MM/DD HH24:MI:SS'), SUBSTR_AFTER(END_TIME, 'B+D') * 86400)
            WHEN END_TIME LIKE 'B+W%'                          THEN ADD_SECONDS(TO_TIMESTAMP(BEGIN_TIME, 'YYYY/MM/DD HH24:MI:SS'), SUBSTR_AFTER(END_TIME, 'B+W') * 86400 * 7)
            WHEN END_TIME LIKE '____/__/__'                    THEN TO_TIMESTAMP(END_TIME || CHAR(32) || '00:00:00', 'YYYY/MM/DD HH24:MI:SS')
            WHEN END_TIME =    'MAX'                           THEN TO_TIMESTAMP('9999/12/31 00:00:00', 'YYYY/MM/DD HH24:MI:SS')
            WHEN SUBSTR(END_TIME, 1, 1) NOT IN ('C', 'B', 'M') THEN TO_TIMESTAMP(END_TIME, 'YYYY/MM/DD HH24:MI:SS')
          END END_TIME,
          TIMEZONE,
          SITE_ID,
          HOST,
          PORT,
          EXCLUDE_STANDBY,
          MIN_CPU_PCT,
          MIN_SYS_CPU_PCT,
          MIN_VERSIONS,
          MIN_PING_MS,
          MIN_HANDLES,
          MIN_REJECTIONS_PER_S,
          MIN_QUEUE_SIZE,
          AGGREGATE_BY,
          DATA_SOURCE,
          MAP(TIME_AGGREGATE_BY,
            'NONE',        'YYYY/MM/DD HH24:MI:SS',
            'HOUR',        'YYYY/MM/DD HH24',
            'DAY',         'YYYY/MM/DD (DY)',
            'HOUR_OF_DAY', 'HH24',
            TIME_AGGREGATE_BY ) TIME_AGGREGATE_BY
        FROM
        ( SELECT                      /* Modification section */
            ? BEGIN_TIME,                  /* YYYY/MM/DD HH24:MI:SS timestamp, C, C-S<seconds>, C-M<minutes>, C-H<hours>, C-D<days>, C-W<weeks>, E-S<seconds>, E-M<minutes>, E-H<hours>, E-D<days>, E-W<weeks>, MIN */
            ? END_TIME,                    /* YYYY/MM/DD HH24:MI:SS timestamp, C, C-S<seconds>, C-M<minutes>, C-H<hours>, C-D<days>, C-W<weeks>, B+S<seconds>, B+M<minutes>, B+H<hours>, B+D<days>, B+W<weeks>, MAX */
            'SERVER' TIMEZONE,                              /* SERVER, UTC */
            -1 SITE_ID,
            '%' HOST,
            '%' PORT,
            'X' EXCLUDE_STANDBY,
            -1 MIN_CPU_PCT,
            -1 MIN_SYS_CPU_PCT,
            -1 MIN_VERSIONS,
            -1 MIN_PING_MS,
            -1 MIN_HANDLES,
            -1 MIN_REJECTIONS_PER_S,
            -1 MIN_QUEUE_SIZE,
            'CURRENT' DATA_SOURCE,           /* CURRENT, HISTORY */
            'TIME' AGGREGATE_BY,               /* TIME, SITE_ID, HOST, PORT and comma separated combinations, NONE for no aggregation */
            ? TIME_AGGREGATE_BY     /* HOUR, DAY, HOUR_OF_DAY or database time pattern, TS<seconds> for time slice, NONE for no aggregation */
          FROM
            DUMMY
        )
      ) BI INNER JOIN
      ( SELECT
          'CURRENT' DATA_SOURCE,
          TIME,
          CURRENT_SITE_ID() SITE_ID,
          HOST,
          PORT,
          PING_TIME,
          CPU,
          SYSTEM_CPU,
          MEMORY_USED,
          SWAP_IN,
          GREATEST(0, CONNECTION_COUNT) CONNECTIONS,
          GREATEST(0, TRANSACTION_COUNT) TRANSACTIONS,
          GREATEST(0, BLOCKED_TRANSACTION_COUNT) BLOCKED_TRANSACTIONS,
          GREATEST(0, STATEMENT_COUNT) STATEMENTS,
          COMMIT_ID_RANGE,
          GREATEST(0, MVCC_VERSION_COUNT) VERSIONS,
          GREATEST(0, PENDING_SESSION_COUNT) PENDING_SESSIONS,
          GREATEST(0, RECORD_LOCK_COUNT) RECORD_LOCKS,
          GREATEST(0, ACTIVE_THREAD_COUNT) ACTIVE_THREADS,
          GREATEST(0, ACTIVE_SQL_EXECUTOR_COUNT) ACTIVE_SQL_EXECUTORS,
          GREATEST(0, WAITING_THREAD_COUNT) WAITING_THREADS,
          GREATEST(0, WAITING_SQL_EXECUTOR_COUNT) WAITING_SQL_EXECUTORS,
          GREATEST(0, CS_MERGE_COUNT) MERGES,
          GREATEST(0, CS_UNLOAD_COUNT) UNLOADS,
          HANDLE_COUNT HANDLES,
          ADMISSION_CONTROL_ADMIT_COUNT ADMISSION_CONTROL_ADMITS,
          ADMISSION_CONTROL_REJECT_COUNT ADMISSION_CONTROL_REJECTS,
          ADMISSION_CONTROL_QUEUE_SIZE,
          ADMISSION_CONTROL_WAIT_TIME,
          NANO100_BETWEEN(LEAD(TIME, 1) OVER (PARTITION BY HOST, PORT ORDER BY TIME DESC), TIME) / 10000000 INTERVAL_S
        FROM
          M_LOAD_HISTORY_SERVICE
        UNION ALL
        SELECT
          'HISTORY' DATA_SOURCE,
          TIME,
          SITE_ID,
          HOST,
          PORT,
          PING_TIME,
          CPU,
          SYSTEM_CPU,
          MEMORY_USED,
          SWAP_IN,
          GREATEST(0, CONNECTION_COUNT) CONNECTIONS,
          GREATEST(0, TRANSACTION_COUNT) TRANSACTIONS,
          GREATEST(0, BLOCKED_TRANSACTION_COUNT) BLOCKED_TRANSACTIONS,
          GREATEST(0, STATEMENT_COUNT) STATEMENTS,
          COMMIT_ID_RANGE,
          GREATEST(MVCC_VERSION_COUNT) VERSIONS,
          GREATEST(0, PENDING_SESSION_COUNT) PENDING_SESSIONS,
          GREATEST(0, RECORD_LOCK_COUNT) RECORD_LOCKS,
          GREATEST(0, ACTIVE_THREAD_COUNT) ACTIVE_THREADS,
          GREATEST(0, ACTIVE_SQL_EXECUTOR_COUNT) ACTIVE_SQL_EXECUTORS,
          GREATEST(0, WAITING_THREAD_COUNT) WAITING_THREADS,
          GREATEST(0, WAITING_SQL_EXECUTOR_COUNT) WAITING_SQL_EXECUTORS,
          GREATEST(0, CS_MERGE_COUNT) MERGES,
          GREATEST(0, CS_UNLOAD_COUNT) UNLOADS,
          HANDLE_COUNT HANDLES,
          ADMISSION_CONTROL_ADMIT_COUNT ADMISSION_CONTROL_ADMITS,
          ADMISSION_CONTROL_REJECT_COUNT ADMISSION_CONTROL_REJECTS,
          ADMISSION_CONTROL_QUEUE_SIZE,
          ADMISSION_CONTROL_WAIT_TIME,
          NANO100_BETWEEN(LEAD(TIME, 1) OVER (PARTITION BY SITE_ID, HOST, PORT ORDER BY TIME DESC), TIME) / 10000000 INTERVAL_S
        FROM
          _SYS_STATISTICS.HOST_LOAD_HISTORY_SERVICE
      ) L ON
        ( BI.SITE_ID = -1 OR L.SITE_ID = BI.SITE_ID ) AND
          L.HOST LIKE BI.HOST AND
          TO_VARCHAR(L.PORT) LIKE BI.PORT AND
          CASE BI.TIMEZONE WHEN 'UTC' THEN ADD_SECONDS(L.TIME, SECONDS_BETWEEN(CURRENT_TIMESTAMP, CURRENT_UTCTIMESTAMP)) ELSE L.TIME END BETWEEN BI.BEGIN_TIME AND BI.END_TIME AND
          L.DATA_SOURCE = BI.DATA_SOURCE LEFT OUTER JOIN
        M_SERVICES S ON
          S.HOST = L.HOST AND
          S.SERVICE_NAME = 'indexserver'
      WHERE
        ( BI.EXCLUDE_STANDBY = ' ' OR S.COORDINATOR_TYPE IS NULL OR S.COORDINATOR_TYPE != 'STANDBY' )
      GROUP BY
        L.TIME,
        L.SITE_ID,
        L.HOST,
        CASE WHEN BI.AGGREGATE_BY = 'NONE' OR INSTR(BI.AGGREGATE_BY, 'PORT') != 0 THEN TO_VARCHAR(L.PORT) ELSE MAP(BI.PORT, '%', 'any', BI.PORT) END,
        BI.SITE_ID,
        BI.HOST,
        BI.MIN_CPU_PCT,
        BI. MIN_SYS_CPU_PCT,
        BI.MIN_VERSIONS,
        BI.MIN_PING_MS,
        BI.MIN_HANDLES,
        BI.MIN_REJECTIONS_PER_S,
        BI.MIN_QUEUE_SIZE,
        BI.TIMEZONE,
        BI.AGGREGATE_BY,
        BI.TIME_AGGREGATE_BY
    )
    GROUP BY
      SAMPLE_TIME,
      CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'SITE_ID') != 0 THEN TO_VARCHAR(SITE_ID) ELSE MAP(BI_SITE_ID, -1, 'any', TO_VARCHAR(BI_SITE_ID)) END,
      CASE WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'HOST') != 0 THEN HOST ELSE MAP(BI_HOST, '%', 'any', BI_HOST) END,
      PORT,
      AGGREGATE_BY,
      MIN_CPU_PCT,
      MIN_SYS_CPU_PCT,
      MIN_VERSIONS,
      MIN_PING_MS,
      MIN_HANDLES,
      MIN_REJECTIONS_PER_S,
      MIN_QUEUE_SIZE,
      TIMEZONE,
      AGGREGATE_BY,
      TIME_AGGREGATE_BY
  )
  GROUP BY
    CASE 
      WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'TIME') != 0 THEN 
        CASE 
          WHEN TIME_AGGREGATE_BY LIKE 'TS%' THEN
            TO_VARCHAR(ADD_SECONDS(TO_TIMESTAMP('2014/01/01 00:00:00', 'YYYY/MM/DD HH24:MI:SS'), FLOOR(SECONDS_BETWEEN(TO_TIMESTAMP('2014/01/01 00:00:00', 
            'YYYY/MM/DD HH24:MI:SS'), CASE TIMEZONE WHEN 'UTC' THEN ADD_SECONDS(SAMPLE_TIME, SECONDS_BETWEEN(CURRENT_TIMESTAMP, CURRENT_UTCTIMESTAMP)) ELSE SAMPLE_TIME END) / SUBSTR(TIME_AGGREGATE_BY, 3)) * SUBSTR(TIME_AGGREGATE_BY, 3)), 'YYYY/MM/DD HH24:MI:SS')
          ELSE TO_VARCHAR(CASE TIMEZONE WHEN 'UTC' THEN ADD_SECONDS(SAMPLE_TIME, SECONDS_BETWEEN(CURRENT_TIMESTAMP, CURRENT_UTCTIMESTAMP)) ELSE SAMPLE_TIME END, TIME_AGGREGATE_BY)
        END
      ELSE 'any' 
    END,
    SITE_ID,
    HOST,
    PORT,
    MIN_CPU_PCT,
    MIN_SYS_CPU_PCT,
    MIN_VERSIONS,
    MIN_PING_MS,
    MIN_HANDLES,
    MIN_REJECTIONS_PER_S,
    MIN_QUEUE_SIZE
)
WHERE
  ( MIN_CPU_PCT = -1 OR CPU_PCT >= MIN_CPU_PCT ) AND
  ( MIN_SYS_CPU_PCT = -1 OR SYS_CPU_PCT >= MIN_SYS_CPU_PCT ) AND
  ( MIN_VERSIONS = -1 OR VERSIONS >= MIN_VERSIONS ) AND
  ( MIN_PING_MS = -1 OR PING_MS >= MIN_PING_MS ) AND
  ( MIN_HANDLES = -1 OR HANDLES >= MIN_HANDLES ) AND
  ( MIN_REJECTIONS_PER_S = -1 OR ADMISSION_CONTROL_REJECTS / INTERVAL_S >= MIN_REJECTIONS_PER_S ) AND
  ( MIN_QUEUE_SIZE = 0 OR ADMISSION_CONTROL_QUEUE_SIZE >= MIN_QUEUE_SIZE )
ORDER BY
  SAMPLE_TIME DESC,
  SITE_ID,
  HOST,
  PORT
    `;

    const queryParams = [
      safeBeginTime,
      safeEndTime,
      safeTimeAggregateBy
    ];

    // Add logging for debugging
    console.log('Executing active sessions query:', {
      query: query.substring(0, 100) + '...',
      params: queryParams,
      filters: {
        beginTime: safeBeginTime,
        endTime: safeEndTime,
        timeAggregateBy: safeTimeAggregateBy
      }
    });

    const result = await executeQuery(query, queryParams);
    
    // Add result count logging
    const sessionCount = Array.isArray(result) ? result.length : 0;
    console.log(`Found ${sessionCount} active sessions`);
    
    return formatQueryResult(result, 'Active Sessions');
  } catch (error) {
    console.error('Active sessions query failed:', error);
    return createErrorResponse(`Active sessions query failed: ${error instanceof Error ? error.message : String(error)}`);
  }
}
