import { executeQuery, formatQueryResult, createErrorResponse, ToolResponse } from '../lib/utils';

export interface handleResources_CPUAndMemory {
  beginTime?: string;
  endTime?: string;
  aggregationType?: string;
  timeAggregateBy?: string;
}

export async function handleResources_CPUAndMemory(params: handleResources_CPUAndMemory = {}): Promise<ToolResponse> {
  try {
    // 파라미터 보정: 빈값(null, undefined, '')이면 기본값 할당
    const beginTime = params?.beginTime ? `'${params.beginTime}'` : `'C-H1'`;
    const endTime = params?.endTime ? `'${params.endTime}'` : `'C'`;    
    const aggregationType = params?.aggregationType ? `'${params.aggregationType}'` : `'AVG'`;
    
    // timeAggregateBy 허용값 체크
    let rawTimeAggregateBy = params?.timeAggregateBy;
    let allowedTimeAggregates = ['HOUR', 'DAY', 'HOUR_OF_DAY', 'NONE'];
    let isTS = typeof rawTimeAggregateBy === 'string' && /^TS\d+$/.test(rawTimeAggregateBy);
    if (rawTimeAggregateBy && !allowedTimeAggregates.includes(rawTimeAggregateBy) && !isTS) {
      return createErrorResponse(
        `timeAggregateBy 파라미터는 'HOUR', 'DAY', 'HOUR_OF_DAY', /^TS\\d+$/, 'NONE' 만 허용합니다. (입력값: ${rawTimeAggregateBy})`
      );
    }
    const timeAggregateBy = rawTimeAggregateBy ? `'${rawTimeAggregateBy}'` : `'TS60'`;

    let query = `
SELECT
  SNAPSHOT_TIME,
  IFNULL(LPAD(SITE_ID, 2), '') ST,
  HOST,
  MEM_AGG,
  LPAD(TO_DECIMAL(MEM_FREE_GB + MEM_USED_GB, 10, 2), 13) PHYS_TOTAL_GB,
  LPAD(TO_DECIMAL(MEM_USED_GB, 10, 2), 12) PHYS_USED_GB,
  LPAD(TO_DECIMAL(MAP(MEM_FREE_GB + MEM_USED_GB, 0, 0, MEM_USED_GB / (MEM_FREE_GB + MEM_USED_GB) * 100), 10, 2), 13) PHYS_USED_PCT,
  LPAD(TO_DECIMAL(ALLOC_LIM_GB, 10, 2), 12) ALLOC_LIM_GB,
  LPAD(TO_DECIMAL(HANA_MEM_ALLOC_GB, 10, 2), 13) HANA_ALLOC_GB,
  LPAD(TO_DECIMAL(HANA_MEM_USED_GB, 10, 2), 12) HANA_USED_GB,
  LPAD(TO_DECIMAL(MAP(ALLOC_LIM_GB, 0, 0, HANA_MEM_USED_GB / ALLOC_LIM_GB * 100), 10, 2), 13) HANA_USED_PCT,
  LPAD(TO_DECIMAL(SWAP_FREE_GB, 10, 2), 12) SWAP_FREE_GB,
  LPAD(TO_DECIMAL(SWAP_USED_GB, 10, 2), 12) SWAP_USED_GB,
  LPAD(TO_DECIMAL(MAP(CPU_TOTAL_S, 0, 0, (CPU_USER_S + CPU_SYS_S) / CPU_TOTAL_S * 100), 10, 2), 7) CPU_PCT,
  LPAD(TO_DECIMAL(MAP(CPU_TOTAL_S, 0, 0, CPU_SYS_S / CPU_TOTAL_S * 100), 10, 2), 11) CPU_SYS_PCT,
  LPAD(TO_DECIMAL(MAP(INTERVAL_S, 0, 0, CPU_USER_S / INTERVAL_S), 10, 2), 8) CPU_USER,
  LPAD(TO_DECIMAL(MAP(INTERVAL_S, 0, 0, CPU_SYS_S / INTERVAL_S), 10, 2), 7) CPU_SYS,
  LPAD(TO_DECIMAL(MAP(INTERVAL_S, 0, 0, CPU_IOWAIT_S / INTERVAL_S), 10, 2), 10) CPU_IOWAIT,
  LPAD(TO_DECIMAL(MAP(INTERVAL_S, 0, 0, CPU_IDLE_S / INTERVAL_S), 10, 2), 8) CPU_IDLE
FROM
( SELECT
    CASE 
      WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'TIME') != 0 THEN 
        CASE 
          WHEN TIME_AGGREGATE_BY LIKE 'TS%' THEN
            TO_VARCHAR(ADD_SECONDS(TO_TIMESTAMP('2014/01/01 00:00:00', 'YYYY/MM/DD HH24:MI:SS'), FLOOR(SECONDS_BETWEEN(TO_TIMESTAMP('2014/01/01 00:00:00', 
            'YYYY/MM/DD HH24:MI:SS'), SNAPSHOT_TIME) / SUBSTR(TIME_AGGREGATE_BY, 3)) * SUBSTR(TIME_AGGREGATE_BY, 3)), 'YYYY/MM/DD HH24:MI:SS')
          ELSE TO_VARCHAR(SNAPSHOT_TIME, TIME_AGGREGATE_BY)
        END
      ELSE 'any' 
    END SNAPSHOT_TIME,
    SITE_ID,
    HOST,
    AGGREGATION_TYPE MEM_AGG,
    MAP(AGGREGATION_TYPE, 'AVG', AVG(ALLOCATION_LIMIT / 1024 / 1024 / 1024), MAX(ALLOCATION_LIMIT / 1024 / 1024 / 1024)) ALLOC_LIM_GB,
    MAP(AGGREGATION_TYPE, 'AVG', AVG(USED_PHYSICAL_MEMORY / 1024 / 1024 / 1024), MAX(USED_PHYSICAL_MEMORY / 1024 / 1024 / 1024)) MEM_USED_GB,
    MAP(AGGREGATION_TYPE, 'AVG', AVG(FREE_PHYSICAL_MEMORY / 1024 / 1024 / 1024), MIN(FREE_PHYSICAL_MEMORY / 1024 / 1024 / 1024)) MEM_FREE_GB,
    MAP(AGGREGATION_TYPE, 'AVG', AVG(INSTANCE_TOTAL_MEMORY_ALLOCATED_SIZE / 1024 / 1024 / 1024), MAX(INSTANCE_TOTAL_MEMORY_ALLOCATED_SIZE / 1024 / 1024 / 1024)) HANA_MEM_ALLOC_GB,
    MAP(AGGREGATION_TYPE, 'AVG', AVG(INSTANCE_TOTAL_MEMORY_USED_SIZE / 1024 / 1024 / 1024), MAX(INSTANCE_TOTAL_MEMORY_USED_SIZE / 1024 / 1024 / 1024)) HANA_MEM_USED_GB,
    MAP(AGGREGATION_TYPE, 'AVG', AVG(USED_SWAP_SPACE / 1024 / 1024 / 1024), MAX(USED_SWAP_SPACE / 1024 / 1024 / 1024)) SWAP_USED_GB,
    MAP(AGGREGATION_TYPE, 'AVG', AVG(FREE_SWAP_SPACE / 1024 / 1024 / 1024), MIN(FREE_SWAP_SPACE / 1024 / 1024 / 1024)) SWAP_FREE_GB,
    SUM(SNAPSHOT_DELTA / 1000) INTERVAL_S,
    SUM(TOTAL_CPU_IDLE_TIME / 1000) CPU_IDLE_S,
    SUM(TOTAL_CPU_SYSTEM_TIME / 1000) CPU_SYS_S,
    SUM(TOTAL_CPU_USER_TIME / 1000) CPU_USER_S,
    SUM(TOTAL_CPU_WIO_TIME / 1000) CPU_IOWAIT_S,
    SUM(TOTAL_CPU_IDLE_TIME + TOTAL_CPU_SYSTEM_TIME + TOTAL_CPU_USER_TIME + TOTAL_CPU_WIO_TIME) / 1000 CPU_TOTAL_S,
    ORDER_BY,
    ONLY_SWAP_SPACE_USED,
    MIN_MEMORY_UTILIZATION_PCT,
    MIN_CPU_UTILIZATION_PCT,
    MIN_SYSTEM_CPU_UTILIZATION_PCT
  FROM
  ( SELECT
      CASE WHEN BI.AGGREGATE_BY = 'NONE' OR LOCATE(BI.AGGREGATE_BY, 'SITE_ID') != 0 THEN TO_VARCHAR(O.SITE_ID) ELSE MAP(BI.SITE_ID,  -1, 'any', TO_VARCHAR(BI.SITE_ID)) END SITE_ID,
      CASE WHEN BI.AGGREGATE_BY = 'NONE' OR LOCATE(BI.AGGREGATE_BY, 'HOST') != 0 THEN O.HOST ELSE MAP(BI.HOST, '%', 'any', BI.HOST) END HOST,
      MIN(CASE BI.TIMEZONE WHEN 'UTC' THEN ADD_SECONDS(O.SNAPSHOT_TIME, SECONDS_BETWEEN(CURRENT_TIMESTAMP, CURRENT_UTCTIMESTAMP)) ELSE O.SNAPSHOT_TIME END) SNAPSHOT_TIME,
      SUM(O.ALLOCATION_LIMIT) ALLOCATION_LIMIT,
      SUM(O.USED_PHYSICAL_MEMORY) USED_PHYSICAL_MEMORY,
      SUM(O.INSTANCE_TOTAL_MEMORY_ALLOCATED_SIZE) INSTANCE_TOTAL_MEMORY_ALLOCATED_SIZE,
      SUM(O.INSTANCE_TOTAL_MEMORY_USED_SIZE) INSTANCE_TOTAL_MEMORY_USED_SIZE,
      SUM(O.FREE_PHYSICAL_MEMORY) FREE_PHYSICAL_MEMORY,
      SUM(O.USED_SWAP_SPACE) USED_SWAP_SPACE,
      SUM(O.FREE_SWAP_SPACE) FREE_SWAP_SPACE,
      AVG(O.SNAPSHOT_DELTA) SNAPSHOT_DELTA,
      SUM(O.TOTAL_CPU_IDLE_TIME) TOTAL_CPU_IDLE_TIME,
      SUM(O.TOTAL_CPU_SYSTEM_TIME) TOTAL_CPU_SYSTEM_TIME,
      SUM(O.TOTAL_CPU_USER_TIME) TOTAL_CPU_USER_TIME,
      SUM(O.TOTAL_CPU_WIO_TIME) TOTAL_CPU_WIO_TIME,
      BI.AGGREGATION_TYPE,
      BI.AGGREGATE_BY,
      BI.TIME_AGGREGATE_BY,
      BI.ORDER_BY,
      BI.ONLY_SWAP_SPACE_USED,
      BI.MIN_MEMORY_UTILIZATION_PCT,
      BI.MIN_CPU_UTILIZATION_PCT,
      BI.MIN_SYSTEM_CPU_UTILIZATION_PCT
    FROM
    ( SELECT
        CASE
          WHEN BEGIN_TIME =    'C'                             THEN CURRENT_TIMESTAMP
          WHEN BEGIN_TIME LIKE 'C-S%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(BEGIN_TIME, 'C-S'))
          WHEN BEGIN_TIME LIKE 'C-M%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(BEGIN_TIME, 'C-M') * 60)
          WHEN BEGIN_TIME LIKE 'C-H%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(BEGIN_TIME, 'C-H') * 3600)
          WHEN BEGIN_TIME LIKE 'C-D%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(BEGIN_TIME, 'C-D') * 86400)
          WHEN BEGIN_TIME LIKE 'C-W%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(BEGIN_TIME, 'C-W') * 86400 * 7)
          WHEN BEGIN_TIME LIKE 'E-S%'                          THEN ADD_SECONDS(TO_TIMESTAMP(END_TIME, 'YYYY/MM/DD HH24:MI:SS'), -SUBSTR_AFTER(BEGIN_TIME, 'E-S'))
          WHEN BEGIN_TIME LIKE 'E-M%'                          THEN ADD_SECONDS(TO_TIMESTAMP(END_TIME, 'YYYY/MM/DD HH24:MI:SS'), -SUBSTR_AFTER(BEGIN_TIME, 'E-M') * 60)
          WHEN BEGIN_TIME LIKE 'E-H%'                          THEN ADD_SECONDS(TO_TIMESTAMP(END_TIME, 'YYYY/MM/DD HH24:MI:SS'), -SUBSTR_AFTER(BEGIN_TIME, 'E-H') * 3600)
          WHEN BEGIN_TIME LIKE 'E-D%'                          THEN ADD_SECONDS(TO_TIMESTAMP(END_TIME, 'YYYY/MM/DD HH24:MI:SS'), -SUBSTR_AFTER(BEGIN_TIME, 'E-D') * 86400)
          WHEN BEGIN_TIME LIKE 'E-W%'                          THEN ADD_SECONDS(TO_TIMESTAMP(END_TIME, 'YYYY/MM/DD HH24:MI:SS'), -SUBSTR_AFTER(BEGIN_TIME, 'E-W') * 86400 * 7)
          WHEN BEGIN_TIME =    'MIN'                           THEN TO_TIMESTAMP('1000/01/01 00:00:00', 'YYYY/MM/DD HH24:MI:SS')
          WHEN SUBSTR(BEGIN_TIME, 1, 1) NOT IN ('C', 'E', 'M') THEN TO_TIMESTAMP(BEGIN_TIME, 'YYYY/MM/DD HH24:MI:SS')
        END BEGIN_TIME,
        CASE
          WHEN END_TIME =    'C'                             THEN CURRENT_TIMESTAMP
          WHEN END_TIME LIKE 'C-S%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(END_TIME, 'C-S'))
          WHEN END_TIME LIKE 'C-M%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(END_TIME, 'C-M') * 60)
          WHEN END_TIME LIKE 'C-H%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(END_TIME, 'C-H') * 3600)
          WHEN END_TIME LIKE 'C-D%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(END_TIME, 'C-D') * 86400)
          WHEN END_TIME LIKE 'C-W%'                          THEN ADD_SECONDS(CURRENT_TIMESTAMP, -SUBSTR_AFTER(END_TIME, 'C-W') * 86400 * 7)
          WHEN END_TIME LIKE 'B+S%'                          THEN ADD_SECONDS(TO_TIMESTAMP(BEGIN_TIME, 'YYYY/MM/DD HH24:MI:SS'), SUBSTR_AFTER(END_TIME, 'B+S'))
          WHEN END_TIME LIKE 'B+M%'                          THEN ADD_SECONDS(TO_TIMESTAMP(BEGIN_TIME, 'YYYY/MM/DD HH24:MI:SS'), SUBSTR_AFTER(END_TIME, 'B+M') * 60)
          WHEN END_TIME LIKE 'B+H%'                          THEN ADD_SECONDS(TO_TIMESTAMP(BEGIN_TIME, 'YYYY/MM/DD HH24:MI:SS'), SUBSTR_AFTER(END_TIME, 'B+H') * 3600)
          WHEN END_TIME LIKE 'B+D%'                          THEN ADD_SECONDS(TO_TIMESTAMP(BEGIN_TIME, 'YYYY/MM/DD HH24:MI:SS'), SUBSTR_AFTER(END_TIME, 'B+D') * 86400)
          WHEN END_TIME LIKE 'B+W%'                          THEN ADD_SECONDS(TO_TIMESTAMP(BEGIN_TIME, 'YYYY/MM/DD HH24:MI:SS'), SUBSTR_AFTER(END_TIME, 'B+W') * 86400 * 7)
          WHEN END_TIME =    'MAX'                           THEN TO_TIMESTAMP('9999/12/31 00:00:00', 'YYYY/MM/DD HH24:MI:SS')
          WHEN SUBSTR(END_TIME, 1, 1) NOT IN ('C', 'B', 'M') THEN TO_TIMESTAMP(END_TIME, 'YYYY/MM/DD HH24:MI:SS')
        END END_TIME,
        TIMEZONE,
        SITE_ID,
        HOST,
        ONLY_SWAP_SPACE_USED,
        MIN_MEMORY_UTILIZATION_PCT,
        MIN_CPU_UTILIZATION_PCT,
        MIN_SYSTEM_CPU_UTILIZATION_PCT,
        EXCLUDE_STANDBY,
        DATA_SOURCE,
        AGGREGATION_TYPE,
        AGGREGATE_BY,
        MAP(TIME_AGGREGATE_BY,
          'NONE',        'YYYY/MM/DD HH24:MI:SS',
          'HOUR',        'YYYY/MM/DD HH24',
          'DAY',         'YYYY/MM/DD (DY)',
          'HOUR_OF_DAY', 'HH24',
          TIME_AGGREGATE_BY ) TIME_AGGREGATE_BY,
        ORDER_BY
      FROM
      ( SELECT                                 /* Modification section */
          ${beginTime} BEGIN_TIME,                  /* YYYY/MM/DD HH24:MI:SS timestamp, C, C-S<seconds>, C-M<minutes>, C-H<hours>, C-D<days>, C-W<weeks>, E-S<seconds>, E-M<minutes>, E-H<hours>, E-D<days>, E-W<weeks>, MIN */
          ${endTime} END_TIME,                    /* YYYY/MM/DD HH24:MI:SS timestamp, C, C-S<seconds>, C-M<minutes>, C-H<hours>, C-D<days>, C-W<weeks>, B+S<seconds>, B+M<minutes>, B+H<hours>, B+D<days>, B+W<weeks>, MAX */
          'SERVER' TIMEZONE,                              /* SERVER, UTC */
          -1 SITE_ID,
          '%' HOST,
          ' ' ONLY_SWAP_SPACE_USED,
          -1 MIN_MEMORY_UTILIZATION_PCT,
          -1 MIN_CPU_UTILIZATION_PCT,
          -1 MIN_SYSTEM_CPU_UTILIZATION_PCT,
          'X' EXCLUDE_STANDBY,
          'HISTORY' DATA_SOURCE,
          ${aggregationType} AGGREGATION_TYPE,           /* AVG, PEAK */
          'SITE_ID, HOST, TIME' AGGREGATE_BY,           /* SITE_ID, HOST, TIME or comma separated list, NONE for no aggregation */
          ${timeAggregateBy} TIME_AGGREGATE_BY,    /* HOUR, DAY, HOUR_OF_DAY or database time pattern, TS<seconds> for time slice, NONE for no aggregation */
          'TIME' ORDER_BY                /* TIME, HOST */
        FROM
          DUMMY
      )
    ) BI INNER JOIN
    ( SELECT
        'CURRENT' DATA_SOURCE,
        CURRENT_TIMESTAMP SNAPSHOT_TIME,
        ( SELECT SECONDS_BETWEEN(MIN(VALUE), CURRENT_TIMESTAMP) * 1000 FROM M_HOST_INFORMATION H WHERE H.KEY = 'start_time' AND H.HOST = R.HOST ) SNAPSHOT_DELTA,
        CURRENT_SITE_ID () SITE_ID,
        HOST,
        FREE_PHYSICAL_MEMORY,
        USED_PHYSICAL_MEMORY,
        FREE_SWAP_SPACE,
        USED_SWAP_SPACE,
        ALLOCATION_LIMIT,
        INSTANCE_TOTAL_MEMORY_USED_SIZE,
        INSTANCE_TOTAL_MEMORY_PEAK_USED_SIZE,
        INSTANCE_TOTAL_MEMORY_ALLOCATED_SIZE,
        INSTANCE_CODE_SIZE,
        INSTANCE_SHARED_MEMORY_ALLOCATED_SIZE,
        TOTAL_CPU_USER_TIME,
        TOTAL_CPU_SYSTEM_TIME,
        TOTAL_CPU_WIO_TIME,
        TOTAL_CPU_IDLE_TIME
      FROM
        M_HOST_RESOURCE_UTILIZATION R
      UNION ALL
      SELECT
        'HISTORY' DATA_SOURCE,
        SERVER_TIMESTAMP SNAPSHOT_TIME,
        SNAPSHOT_DELTA,
        SITE_ID,
        HOST,
        FREE_PHYSICAL_MEMORY,
        USED_PHYSICAL_MEMORY,
        FREE_SWAP_SPACE,
        USED_SWAP_SPACE,
        ALLOCATION_LIMIT,
        INSTANCE_TOTAL_MEMORY_USED_SIZE,
        INSTANCE_TOTAL_MEMORY_PEAK_USED_SIZE,
        INSTANCE_TOTAL_MEMORY_ALLOCATED_SIZE,
        INSTANCE_CODE_SIZE,
        INSTANCE_SHARED_MEMORY_ALLOCATED_SIZE,
        TOTAL_CPU_USER_TIME_DELTA,
        TOTAL_CPU_SYSTEM_TIME_DELTA,
        TOTAL_CPU_WIO_TIME_DELTA,
        TOTAL_CPU_IDLE_TIME_DELTA
      FROM
        _SYS_STATISTICS.HOST_RESOURCE_UTILIZATION_STATISTICS
    ) O ON
        O.DATA_SOURCE = BI.DATA_SOURCE AND
        ( BI.SITE_ID = -1 OR ( BI.SITE_ID = 0 AND O.SITE_ID IN (-1, 0) ) OR O.SITE_ID = BI.SITE_ID ) AND
        O.HOST LIKE BI.HOST AND
        CASE BI.TIMEZONE WHEN 'UTC' THEN ADD_SECONDS(O.SNAPSHOT_TIME, SECONDS_BETWEEN(CURRENT_TIMESTAMP, CURRENT_UTCTIMESTAMP)) ELSE O.SNAPSHOT_TIME END BETWEEN BI.BEGIN_TIME AND BI.END_TIME LEFT OUTER JOIN
      M_LANDSCAPE_HOST_CONFIGURATION S ON
        S.HOST = O.HOST
    WHERE
      ( BI.EXCLUDE_STANDBY = ' ' OR S.INDEXSERVER_ACTUAL_ROLE != 'STANDBY' OR ( SELECT COUNT(*) FROM M_LANDSCAPE_HOST_CONFIGURATION ) = 0 )
    GROUP BY
      O.SNAPSHOT_TIME,
      CASE WHEN BI.AGGREGATE_BY = 'NONE' OR LOCATE(BI.AGGREGATE_BY, 'SITE_ID') != 0 THEN TO_VARCHAR(O.SITE_ID) ELSE MAP(BI.SITE_ID,  -1, 'any', TO_VARCHAR(BI.SITE_ID)) END,
      CASE WHEN BI.AGGREGATE_BY = 'NONE' OR LOCATE(BI.AGGREGATE_BY, 'HOST') != 0 THEN O.HOST ELSE MAP(BI.HOST, '%', 'any', BI.HOST) END,
      BI.AGGREGATION_TYPE,
      BI.AGGREGATE_BY,
      BI.TIME_AGGREGATE_BY,
      BI.ORDER_BY,
      BI.ONLY_SWAP_SPACE_USED,
      BI.MIN_MEMORY_UTILIZATION_PCT,
      BI.MIN_CPU_UTILIZATION_PCT,
      BI.MIN_SYSTEM_CPU_UTILIZATION_PCT
  )
  GROUP BY
    CASE 
      WHEN AGGREGATE_BY = 'NONE' OR INSTR(AGGREGATE_BY, 'TIME') != 0 THEN 
        CASE 
          WHEN TIME_AGGREGATE_BY LIKE 'TS%' THEN
            TO_VARCHAR(ADD_SECONDS(TO_TIMESTAMP('2014/01/01 00:00:00', 'YYYY/MM/DD HH24:MI:SS'), FLOOR(SECONDS_BETWEEN(TO_TIMESTAMP('2014/01/01 00:00:00', 
            'YYYY/MM/DD HH24:MI:SS'), SNAPSHOT_TIME) / SUBSTR(TIME_AGGREGATE_BY, 3)) * SUBSTR(TIME_AGGREGATE_BY, 3)), 'YYYY/MM/DD HH24:MI:SS')
          ELSE TO_VARCHAR(SNAPSHOT_TIME, TIME_AGGREGATE_BY)
        END
      ELSE 'any' 
    END,
    AGGREGATION_TYPE,
    SITE_ID,
    HOST,
    ORDER_BY,
    ONLY_SWAP_SPACE_USED,
    MIN_MEMORY_UTILIZATION_PCT,
    MIN_CPU_UTILIZATION_PCT,
    MIN_SYSTEM_CPU_UTILIZATION_PCT
) O
WHERE
  ( ONLY_SWAP_SPACE_USED = ' ' AND MIN_MEMORY_UTILIZATION_PCT = -1 AND MIN_CPU_UTILIZATION_PCT = -1 AND MIN_SYSTEM_CPU_UTILIZATION_PCT = -1 ) OR
  ( ONLY_SWAP_SPACE_USED = 'X' AND TO_DECIMAL(ROUND(O.SWAP_USED_GB), 10, 0) > 0 ) OR
  ( MIN_MEMORY_UTILIZATION_PCT != -1 AND MAP(ALLOC_LIM_GB, 0, 0, HANA_MEM_USED_GB / ALLOC_LIM_GB * 100) >= MIN_MEMORY_UTILIZATION_PCT ) OR
  ( MIN_CPU_UTILIZATION_PCT != -1 AND MAP(O.CPU_TOTAL_S, 0, 0, (O.CPU_SYS_S + O.CPU_USER_S) / O.CPU_TOTAL_S * 100) >= MIN_CPU_UTILIZATION_PCT ) OR
  ( MIN_SYSTEM_CPU_UTILIZATION_PCT != -1 AND MAP(O.CPU_TOTAL_S, 0, 0, O.CPU_SYS_S / O.CPU_TOTAL_S * 100) >= MIN_SYSTEM_CPU_UTILIZATION_PCT )
ORDER BY
  MAP(ORDER_BY, 'HOST', HOST),
  SNAPSHOT_TIME DESC,
  SITE_ID,
  HOST
    `;

    const result = await executeQuery(query);
    return formatQueryResult(result, '');
  } catch (error) {
    return createErrorResponse(`조회 실패: ${error instanceof Error ? error.message : String(error)}`);
  }
}
